### ISSUE TITLE
Bluetooth problem

### ISSUE THREAD

**Issue by Menchen** [daliansky/XiaoMi-Pro#101]
Hi, yesterday I opened up my laptop and inserted wifi card from taobao, and tried solder usb cable(probably bad soldering skill... Can I solder like one to pin 3,4 and other one on pin 5,6?). After replaced usbport kext I still cannot get Bluetooth working.. not showing in system information/ Bluetooth  nor in usb. Wifi is working good.  Also I noticed that touchpad is a little "soft" is it problem about battery screw (too soft )?

**Comment by stevezhengshiqi** [comment]
@Menchen Hi, D+ have to be soldered into pin4 and D- to pin5. These two pins are only two pins for USB protocol. I think there are two things you can do.
- Check whether there are kexts called `USBPower` or `USBInjectAll` in `CLOVER/kexts/Other`. If yes, you have to delete them.
- Go to Windows or use IORegistryExplorer to check USB ports. You can generate an ioreg file and send back to me.
[IORegistryExplorer.app.zip](https://github.com/daliansky/XiaoMi-Pro/files/2569228/IORegistryExplorer.app.zip)

**Comment by Menchen** [comment]
I'm sure I have soldered at these pins, what I'm not sure is maybe it have a bridge with 3 and 4 ; 5 and 6....

IOReg after delete USBPorts, no USBPower nor USBInjectAll.
[IOReg.zip](https://github.com/daliansky/XiaoMi-Pro/files/2569399/IOReg.zip)

**Comment by stevezhengshiqi** [comment]
@Menchen In your `IOR with USBPort`, I see port `HS02` is enabled, which is for WLAN_LTE USB. Technically, BT should work if you soldered correctly. Maybe you can go into Windows or other OS to verify that your solder process is successful or not.

For softer trackpad, I can help little. The driver `VoodooI2C` is from https://github.com/alexandred/VoodooI2C, and I have limited knowledge about how it works. You can create an issue at https://github.com/alexandred/VoodooI2C/issues to get professional help.

**Comment by Menchen** [comment]
@stevezhengshiqi  After booting into Linux, There is only one Bluetooth device, so It must be soldering problem (Or linux driver?). Also the intel one didn't shown on lsusb and lspcie....

About the trackpad, what I meant is that it's physically soft (a small gaps, and it move with little force without click ), Is it normal as we added antenna under it or it's just me?

Also it's safe to bridge when soldering pin? like 3 with 4 and 5 with 6..... Because I have no prior soldering experience and it's too small..

Thank you for your time.

**Comment by Menchen** [comment]
@stevezhengshiqi I have tried to solder another time.. and I have made sure that the pin is correctly solder using a multimeter... I'm using  the kext in wiki with `SolderBT`(md5 end with 08aaeadb2e1) and HS02 is not showing in ioreg(only 1,3,4 and 9 ,nothing plugged beside power source).. so maybe wrong kext or....
I will update full log ASAP as I'm currently using phone data without wifi... (btw I changed thermal paste and it solve the thermal throttles, at full load instead 100c, now it's 75c, and 5c differences in idle.)

Thanks you for your time.
