### ISSUE TITLE
Headphones on jack issue

### ISSUE THREAD

**Issue by Vichearith** [daliansky/XiaoMi-Pro#104]
Hi everyone :)
I have problem with headphones connected on jack. I used ALC fix plug, and nothing.
Example: when I reboot MacOS and I put a video, I don't hear anything. Doesn't work since I moved to Mojave
I tried :
- To replug the earphone after every reboot.
- To replace EFI/CLOVER/kexts/Other/CodecCommander.kext
I'm on Mojave 10.14.1
Thx for help :)

**Comment by Menchen** [comment]
Try to backup and replace the entire EFI? Running Mojave and it 's working for me(need replug each sleep )..... 
Also try to rebuild cache after update...

**Comment by Vichearith** [comment]
How can I replace the entire EFI ? Do you have a tutorial ?

**Comment by Menchen** [comment]
Yes... just backup old one first...

**Comment by Vichearith** [comment]
Still doesn't work 😢

**Comment by Menchen** [comment]
I7 or i5 model?

**Comment by Vichearith** [comment]
i7 model

**Comment by paajake** [comment]
Did you leave the jack connected while you restart ?

**Comment by Vichearith** [comment]
No I unplug the jack while I restart

**Comment by Vichearith** [comment]
I delete Audiojingle (https://discussions.apple.com/thread/8173543) and restart with the jack unplug and it works

**Comment by paajake** [comment]
A restart with the jack connected before restart, and the a remove and reconnect of jack on boot, and it works for me

**Comment by stevezhengshiqi** [comment]
@Menchen It’s strange that you need replug everysleep. Did you pause the song before sleep?

**Comment by Menchen** [comment]
@stevezhengshiqi, My bad it work with sleep but not with hibernation.
