### ISSUE TITLE
right click is not working 

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro#105]
hello
is some strange way the track pad is working fine but I don't have right click with two fingers click as it says in the settings of the track pad 
any thing I'm doing wrong?

**Comment by Menchen** [comment]
For me, two finger touch is working, but not two finger click.

**Comment by stevezhengshiqi** [comment]
Yes, two finger click is not working. It’s a VoodooI2C problem which I am not able to fix. You can use two finger touch instead.

**Comment by macguru341** [comment]
great - thanks !!!!!

**Comment by shyim** [comment]
![Screenshot 2019-04-20 at 18 45 50](https://user-images.githubusercontent.com/6224096/56460031-a2452800-639c-11e9-89ef-193bf12c0002.png)
![Screenshot 2019-04-20 at 18 46 04](https://user-images.githubusercontent.com/6224096/56460032-a2452800-639c-11e9-95cf-eceb35a362f5.png)
![Screenshot 2019-04-20 at 18 46 15](https://user-images.githubusercontent.com/6224096/56460033-a2452800-639c-11e9-92d7-27d35e43706c.png)

I have the same issue. Touching with two fingers is not working. Any idea?

**Comment by stevezhengshiqi** [comment]
@shyim Hi, you also need to check `Tap to click` if you want two-finger touch.
