### ISSUE TITLE
请问一下，13升14的话有具体流程吗？

### ISSUE THREAD

**Issue by alex-czp** [daliansky/XiaoMi-Pro#106]
求大佬给个思路，甩个教程过来就更好了

**Comment by stevezhengshiqi** [comment]
如果你是小米Pro+v1.2.8 EFI release，就在AppStore搜索 Mojave, 然后点击更新按钮。

更新完成后用 KextUtility 或者用README里提到的命令重建缓存来激活触控板。

**Comment by alex-czp** [comment]
@stevezhengshiqi 多谢大佬，我还以为要像重新装一次那样折腾一轮，原来这样就可以了呀
