### ISSUE TITLE
Enable Handoff with external Bluetooth dongle

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro#108]
Hello
I have external Bluetooth dongle that works great , connected with apple Magic Mouse , AirPods and sound. I want to enable the handoff option and it’s turned on on my iPhone and the iPhone is on the same network as the pc (mac is connected with LAN cable) and they both uses the same iCloud account but in the Mac general settings I don’t have the option “Allow Handoff between this Mac and your iCloud devices”.
What am I doing worng ?
By the way the internal Bluetooth is disabled

**Comment by Menchen** [comment]
Handoff need wifi+Bluetooth,  so what's your wifi card?

**Comment by macguru341** [comment]
I have also a WiFi dongle ...but with wired connection it’s not working ?

**Comment by Menchen** [comment]
You need internal wifi to get airport/Handoff working....(not sure if that apply to BT too.)..

So you need buy a compatible apple wifi card and using a adaptor to m2, search in this repo issues about more info.
