### ISSUE TITLE
report bug：触摸板在三指切换之后，鼠标会停在那没法动，得等一会才能动，用的是最新版的efi。

### ISSUE THREAD

**Issue by yangxx007** [daliansky/XiaoMi-Pro#11]

**Comment by kvn1351** [comment]
I think that's a new bug of the latest `VoodooI2C`  kext.

That's not something @daliansky can fix. Wait for `VoodooI2C` to get updated.

**Comment by yangxx007** [comment]
ok！got it, @kvn1351 thanks anyway. your native language is english?  or you just used to write in english?

**Comment by kvn1351** [comment]
@yangxx007 Actually, I think it's rather a bug of `ApplePS2SmartTouchPad.kext` as it seems to affect many people on it's forum post. `VoodooI2C` is only responsible for getting the I2C communication across, `ApplePS2SmartTouchPad` then interprets them. This is my understanding of it, but I might be wrong.

Anyway, yeah, I'm Swiss :) so I can't speak Chinese unfortunately - not yet.

**Comment by yangxx007** [comment]
@kvn1351 thanks again, you can't speak Chinese but you still take a lot of time to translate and understand   the meaning of my question .
So is there an updated&stable version or replacement of ApplePS2SmartTouchpad.kext can fix this problem?

**Comment by kvn1351** [comment]
@yangxx007 Not if you want to keep the gesture functionality. If you don't care about that you could try the PS2 controller from @rehabman; but I find it to be much worse than the SmartTouchPad one.

Also, when it locks up, I've found that tapping with all three/four fingers once (quickly) releases the lock. It should work for you too.

**Comment by CRJJared** [comment]
@kvn1351 Three-finger swiping is also not functioning very well. Wasn't it suppoesed to switch between the running programs when swiping?

**Comment by kvn1351** [comment]
@CRJJared Gestures emulate a series of keystrokes; these are hardcoded within the `VoodooI2C` kext. So you either have to change them in there or change the actual keyboard shortcut in macOS's Settings.

https://voodooi2c.github.io/#Supported Gestures/Supported Gestures


Also, I've discovered that I was wrong. `ApplePS2SmartTouchPad` is being used for the keyboard (volume keys and so on) while `VoodooI2C`  is being used by the thouchpad in conjunction with the `VoodooI2CHID` kext for the protocol.


I've also fixed the brightness keys, as reported in the other thread, but @daliansky still hasn't replied :/

**Comment by CRJJared** [comment]
@kvn1351 Sorry, it's working perfectly after I added one more panel. Haha, guess I'm not quite used to macOS. 
<img width="426" alt="qq20180203-223029 2x" src="https://user-images.githubusercontent.com/36077664/35775078-ca74f054-0979-11e8-8804-24e75d5ff18b.png">
As for brightness keys, I tried changing the default shortcuts (f14/f15) to f4/f5, and the brightness control is working as well. I can't quite tell the difference between these and the native keystrokes (fn+f4/f5). 
<img width="432" alt="qq20180203-224539 2x" src="https://user-images.githubusercontent.com/36077664/35775083-d61493ba-0979-11e8-918e-9c97df534070.png">
Appreciate you guys' hard work, thanks!

**Comment by SeunLanLege** [comment]
any idea on when this'll be fixed?

**Comment by macguru341** [comment]
I’m also have lots of issues with the trackpad, it’s not working after reset and I need to put the machine to sleep and wake it up to have it back working, also when it’s working it feels not smooth and very slow slide up and down in webpages

**Comment by stevezhengshiqi** [comment]
It can be fixed by using the newest kexts from @alexandred. However, he refuses to publish them since they are buggy. I guess we can wait or go to his github to build a new one. If system crashes, you have to take the responsibility on your own.

**Comment by alexandred** [comment]
@stevezhengshiqi I'm not sure what bug you're referring to but if you're replying to @macguru341's latest post, this is not the case with v2.0.1. The latest stable version of VoodooI2C does not have sleep issues. There is no "buggy version" that I refuse to release (unless you are referring to the native gestures version which is in no way ready for public consumption).

**Comment by kprinssu** [comment]
@stevezhengshiqi The native version is buggy with VoodooI2CHID. I personally use a customised VoodooI2CELAN and it works with little issues.


The issue I found is that the finger size (touch minor and touch major) are needed for Apple's kexts to distinguish certain gestures. Fortunately,  my trackpad supports the touch minor/major and everything works.

**Comment by stevezhengshiqi** [comment]
@kprinssu That's a great news. I think I am already happy about the stable version. Look forward to the native version and feel grateful to you guys.

**Comment by seunlanlege** [comment]
I'm on the latest commit to master and my trackpad is still wonky, how is it working for you?

**Comment by stevezhengshiqi** [comment]
@seunlanlege Please use the EFI folder in my release https://github.com/stevezhengshiqi/XiaoMi-Pro/releases

**Comment by seunlanlege** [comment]
Your efi folder, broke my trackpad. I've reverted to the master branch of this repo.

**Comment by stevezhengshiqi** [comment]
Please run Kext Utility after using my efi folder

**Comment by seunlanlege** [comment]
So here's the thing I replaced my efi folder with yours.
`sudo rm -rf /System/Library/Extensions/*`
`sudo rm -rf /Library/Extensions/*`
Then rebooted, laptop no longer boots to mac os. Stuck at 100% loading on apple screen.
I thought the kexts are automatically rebuilt on boot?

**Comment by influenist** [comment]
@seunlanlege
Why would you remove all your kext? Your system will not boot without the default Apple kext which are located in /S*/L*/E*.

**Comment by seunlanlege** [comment]
How do i put them back?

**Comment by stevezhengshiqi** [comment]
@seunlanlege Reinstall the whole system.
