### ISSUE TITLE
Problem with keyboard shortcuts

### ISSUE THREAD

**Issue by alexmenn** [daliansky/XiaoMi-Pro#111]
Hello there!
I've changed smbios from 15.2 to 14.1 to fix webcam. If you use 15.2, webcam won't work, then, 14.1 is ok. But after restart, keyboard shortcuts like vol+ or vol-, even brightness + and brightness - shortcuts "stopped working". Now I have to press FN+F3 or FN+F2 to change volumen, and with F4 and F5 to change brightness. I want to restore the last configuration, just clicking F3 instead of FN+F3 to change volume. How can I fix it? I tried to press F2 and F4 in clover too but not success. Kexts seem to be well loaded.

**Comment by stevezhengshiqi** [comment]
Try to press FN + ESC.

**Comment by stevezhengshiqi** [comment]
Because USBPorts is device specific. It only supports MBP14,1.

**Comment by alexmenn** [comment]
Oh okay! Then if one day usbports is compatible with MBP15.2, tell us :) haha

thank you again!

**Comment by stevezhengshiqi** [comment]
@alexmenn There is no solid reason to choose MBP15,2. If you really want to use MBP15,2, open info.plist, find MBP14,1 and replace it with MBP15,2.
