### ISSUE TITLE
acpi hotpatching

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro#112]
@daliansky , thank you very much for making hackintosh for our laptops.

Can I ask something ?
Would it be possible , when you have the time ,to add a description for every aml file and what is for ?

**Comment by stevezhengshiqi** [comment]
Hi, daliansky is so busy these days and I have to prepare SAT test. I recommend that you can read https://github.com/RehabMan/OS-X-Clover-Laptop-Config. What you want is all in there.

**Comment by stevezhengshiqi** [comment]
OK. I understand what you mean. Will do it in a week.

**Comment by stevezhengshiqi** [comment]
Done.

**Comment by Mateo1234454545** [comment]
Great. Thank you.
