### ISSUE TITLE
how Can I modify voodoo to drag objects?

### ISSUE THREAD

**Issue by johnnync13** [daliansky/XiaoMi-Pro#114]
Hello, I have xiaomi mi air and works all less drag

**Comment by stevezhengshiqi** [comment]
Hi, I think [alex](https://github.com/alexandred/VoodooI2C) can give you the most professional answer. You can try to play around settings in `SysPref-Accessibility-TouchPad`.

**Comment by johnnync13** [comment]
Yes, it is correct. Another question, I bought internal wifi apple on taobao, but in my 12,5 air works in port NVME but in my port NVME in air 13.3 not works:(

**Comment by stevezhengshiqi** [comment]
Some of my friends also meet with this problem. We guess that air's BIOS has some kind of whitelist which prevent the wifi from loading.

**Comment by johnnync13** [comment]
@stevezhengshiqi
There are a Forum to unlock bios
https://www.google.es/amp/s/forum.xda-developers.com/windows-10/general/xiaomi-mi-notebook-air-13-2018-8250u-t3839909/amp/

**Comment by stevezhengshiqi** [comment]
Seems great.

**Comment by johnnync13** [comment]
I can't remove whitelist...  Protected Range Registers are currently set by BIOS, preventing flash access. :(

**Comment by FallenChromium** [comment]
@johnnync13 nah, actually it's not a problem, all Xiaomi UEFI BIOS-es are unlockable by the same method as Air 2016, you just need to find the right place to patch.

**Comment by johnnync13** [comment]
I have Error 316: Protected Range Registers are currently set by BIOS, preventing flash access.
Please contact the target system BIOS vendor for an option to disable Protected Range Registers.
I want to remove whiteList :( @FallenChromium 
I could enable undervolting only... there is a tutorial that explain to disable but I have these error..
https://forum.xda-developers.com/showpost.php?p=77690179&postcount=20

**Comment by FallenChromium** [comment]
@johnnync13 so what's the problem? Tutorial seems quite straightforward and simple, if you have unsupported BIOS you can downgrade it. You also can buy SOIC8 clip + USB programmer, so you can do whatever you want with your BIOS, I did so when there was no unlock for XMNBP and unlocked mine myself, also helping Cyb testing his patches. Do this tutorial first. Also, check bios-mods, probably there's a request already to remove whitelist, you can fill one yourself

**Comment by johnnync13** [comment]
I have this problem when I flash bios. I try with P100B too.
<img width="960" alt="5ac7acc2-1592-4915-8b7f-4587e52e446a" src="https://user-images.githubusercontent.com/22727137/49901931-d8105800-fe62-11e8-8423-eae2d9da3c85.png">

**Comment by Menchen** [comment]
> I have this problem when I flash bios. I try with P100B too.
> <img alt="5ac7acc2-1592-4915-8b7f-4587e52e446a" width="960" src="https://user-images.githubusercontent.com/22727137/49901931-d8105800-fe62-11e8-8423-eae2d9da3c85.png">


I think you need unlock bios (manual flash) to solve that error.
See https://github.com/cybsuai/Mi-Notebook-Pro-tweaks

I think this apply for air too, maybe you need find a different nsh file.. idk

**Comment by johnnync13** [comment]
Next week I have some exams. I will comment soon. Thank you for help me !

**Comment by johnnync13** [comment]
I have this problem to H2OUVE.exe -sv AllVarsEdited.txt
<img width="960" alt="image" src="https://user-images.githubusercontent.com/22727137/49945278-c8d5ec80-feec-11e8-8b55-bd90d73453cf.png">
[AllVarsEdited.txt](https://github.com/daliansky/XiaoMi-Pro/files/2676415/AllVarsEdited.txt)

**Comment by stevezhengshiqi** [comment]
@FallenChromium Hi, is it possible to unlock thunderbolt in BIOS of Xiaomi-Pro?

**Comment by johnnync13** [comment]
@FallenChromium @Menchen @orditeck  I extract with ifr extractor and I want to modify bios and flash with USB programmer. This is my variables. 
NVME is in port #9
What do I have to modify?
[setup IFR.txt](https://github.com/daliansky/XiaoMi-Pro/files/2776833/setup.IFR.txt)

**Comment by johnnync13** [comment]
I'm trying to remove whitelist with spi programmer. I change some variables like BIOS GUARD, RTC and more and works great. 
[MiAir.zip](https://github.com/daliansky/XiaoMi-Pro/files/2780994/MiAir.zip)

**Comment by johnnync13** [comment]
I found this variable on bios 
etting: Thunderbolt(TM) PCIe Support, Variable: 0x5BE {05 91 D9 13 DA 13 D1 0A 34 12 BE 05 10 10 00 01 00}
0x162E51 				Option: Disabled, Value: 0x0 {09 07 04 00 30 00 00}<< 30 here denotes "Default" setting, move 30 to above setting instead, in same location, set 00 here in it's place, that is all.
0x162E58 				Option: Enabled, Value: 0x1 {09 07 03 00 00 00 01}

I can enable this.

**Comment by FallenChromium** [comment]
@johnnync13 Don't waste your time, I already tried and as I already wrote several times, looks like there just isn't any PCIe lanes on the USB-C, so physically it won't work

**Comment by johnnync13** [comment]
@FallenChromium I see that with port nvme on air its different on wlan device.
In air is disabled, in Pro is enabled. Will Can I install wifi m2 card?

**Comment by johnnync13** [comment]
@FallenChromium 
In Air
Setting: Wireless device, Variable: 0x587 {05 91 70 0F 71 0F 8D 0A 34 12 87 05 10 10 00 01 00}
0x16307C 				Option: Disabled, Value: 0x0 {09 07 04 00 30 00 00}
0x163083 				Option: Enabled, Value: 0x1 {09 07 03 00 00 00 01}
In PRO
Setting: Wireless device, Variable: 0x587 {05 91 70 0F 71 0F 8D 0A 34 12 87 05 10 10 00 01 00}
0x16307C 				Option: Disabled, Value: 0x0 {09 07 04 00 00 00 00}
0x163083 				Option: Enabled, Value: 0x1 {09 07 03 00 30 00 01}

**Comment by FallenChromium** [comment]
I have a friend With Mi Air 13 2016, and I suppose he'll face with the same WiFI problem, so I want to participate. In 2016 model there's one NVMe slot which is grabbed by stock SSD, second one is SATA-only so it wouldn't work, and also 2244 WWAN\LTE slot which supposedly can be used to have a WiFi card inside, it looks like M.2 Key M at first sight, so technically WiFi adapter from TaoBao should work. I don't know anything about 2017-2018 Air models internals yet, so I can't tell you. More information would be appreciated.
P.S As of BIOS unlock I'd like to get .bin files of BIOS and which scripts are you using, and also model of the laptop

**Comment by johnnync13** [comment]
@FallenChromium In Xiaomi Notebook Air 2016 works m.2 card wifi. In 7200u too. In 8550/8250u not
