### ISSUE TITLE
Bluetooth address 00000000

### ISSUE THREAD

**Issue by Menchen** [daliansky/XiaoMi-Pro#119]
After openup and try soldering again, I got it recognised in mac #101, but unable to discover or be discovered by other device, also no luck with airdrop.

**Comment by Menchen** [comment]
![20181215_164956](https://user-images.githubusercontent.com/6707265/50044844-f6a46800-0089-11e9-83c7-a0936c17cbd7.jpg)

So it's soldering problem or hardware problem or mac problem?

**Comment by stevezhengshiqi** [comment]
Please follow the way in https://github.com/stevezhengshiqi/XiaoMi-Pro/issues/7. If you are using Xiaomi-Pro, you have to disable your native bluetooth to enable other bluetooth module.

**Comment by Menchen** [comment]
> If you are using Xiaomi-Pro, you have to disable your native bluetooth to enable other bluetooth module. Please follow the way in [stevezhengshiqi#7](https://github.com/stevezhengshiqi/XiaoMi-Pro/issues/7).

I'm pretty sure that I have replaced that next... maybe got overwritten when I pull the repo to update efi, after replacing the kext no Bluetooth device found.. so must be something went wrong with soldering.... sorry for that... I will try resolder tomorrow, any tips are welcome.
