### ISSUE TITLE
[Issue] Touchpad again

### ISSUE THREAD

**Issue by frandj99** [daliansky/XiaoMi-Pro#12]
Hello Daliansky, thank you so much for creating this Git for Xiaomi Pro.
Today I've updated EFI in my hackintosh, but I still have problem with touchpad (HDMI and Type C Video works very well)
It worked good for the first time, but after a reboot nothing. I tried also cleaning cache (with Kext Utility), but nothing
What can be my error ?

PS, If I can ask here: I'm thinking about add an m2 wifi card, like the Broadcom BCM94352Z . Can be good ?

Thank you so much in advace ;)

**Comment by kvn1351** [comment]
Be more specific about your problem.

There is no m.2 wifi card with compatible keys unfortunately.

**Comment by frandj99** [comment]
Hehe... right now it does not really work completely.
When I've "upgraded" EFI folder and installed kext was working perfectly. I updated also to lastest version of High Sierra (From 10.13.2 to 10.13.3 or lastest, I don't remember) ad it worked good
I've done a reboot on windows and after touchpad stop working on MacOS (maybe Windows is not the cause, but just the reboot). Is userful to send you something like a ioreg report o something similar?
What I can try ?
Thank you for reply me ;)

**Comment by kvn1351** [comment]
@frandj99 

1. Boot into macOS
2. Terminal > diskutil list 
3. Terminal > diskutil mount /dev/{identifier of EFI patition from step 2}
4. Delete the Clover folder
5. Install Clover again
6. Merge daliansky's folder on top of it
7. Report back

**Comment by frandj99** [comment]
Okay, I tried but it didn't work. I've also tried to install with Kext Utility and delete the old ones on /System/Library/Extensions/
[ioregnew.zip](https://github.com/daliansky/XiaoMi-Pro/files/1694931/ioregnew.zip)

**Comment by kvn1351** [comment]
@frandj99 There isn't anything you should install with Kext Utility.
`/System/` should stay untouched.

**Comment by frandj99** [comment]
Okay, solved. I've delected the PS2 and I2C kext on system and now works perfectly. Thank you so much for time.
I didn't know that we have only to use kext in clover folder, on some forums (The guide linked on Git is in Chinese and Google Translate was not so good for understanding) I found that I had to install so I was wrong.

Thank you again ;)
