### ISSUE TITLE
小米笔记本pro，10.14.2触摸板不能用。

### ISSUE THREAD

**Issue by Freeskylover** [daliansky/XiaoMi-Pro#120]
小米笔记本pro，10.14.2触摸板不能用。重启也无法解决。

**Comment by FallenChromium** [comment]
Did you tried to execute `sudo kextcache -i /` and reboot after that? Helped me.

**Comment by Freeskylover** [comment]
> Did you tried to execute `sudo kextcache -i /` and reboot after that? Helped me.

谢谢你，解决啦。
