### ISSUE TITLE
Can you help me to do SSDT-PXSX and SSDT-PCIList?

### ISSUE THREAD

**Issue by johnnync13** [daliansky/XiaoMi-Pro#123]
@stevezhengshiqi  @daliansky 
This is repository: https://github.com/johnnync13/XiaomiGaming
[Gaming.zip](https://github.com/daliansky/XiaoMi-Pro/files/2687486/Gaming.zip)
And you PXSX is not correct... 
![captura de pantalla 2018-12-17 a las 20 04 39](https://user-images.githubusercontent.com/22727137/50109041-02815d00-0237-11e9-9e1f-1be835a1e619.png)

**Comment by stevezhengshiqi** [comment]
Sure. I will have a look at it later. I am waiting for final report at school recently.

**Comment by johnnync13** [comment]
Good luck!

**Comment by johnnync13** [comment]
@stevezhengshiqi debugs.. the some users
[debug_20930.zip](https://github.com/daliansky/XiaoMi-Pro/files/2694559/debug_20930.zip)
[debug_26777.zip](https://github.com/daliansky/XiaoMi-Pro/files/2694560/debug_26777.zip)

**Comment by stevezhengshiqi** [comment]
Please let the users check their SSD is whether supported or not. A large amount of panic log is about NVME. If they have a PM981, please put it out and then check again.

**Comment by johnnync13** [comment]
They have 970 evo

**Comment by stevezhengshiqi** [comment]
And also try to update MaciASL by using the latest release from https://github.com/acidanthera/MaciASL/releases

**Comment by johnnync13** [comment]
![fb517625-56c5-4863-84b3-0b9ec40cbff9](https://user-images.githubusercontent.com/22727137/50230472-033bff80-03ad-11e9-8321-590f465d7cae.jpeg)
![d2e592e3-01d3-432c-be2d-fea00802c5e5](https://user-images.githubusercontent.com/22727137/50230474-03d49600-03ad-11e9-8492-7d9c8d6b9830.jpeg)
![f105de45-c2e7-42ec-bf10-da71d7335e16](https://user-images.githubusercontent.com/22727137/50230476-03d49600-03ad-11e9-8b44-118ff5599069.jpeg)
![3a1e38b0-0b88-4cef-9aaf-5cd187919210](https://user-images.githubusercontent.com/22727137/50230477-03d49600-03ad-11e9-87a5-6b48e9f0f6f9.jpeg)
![Uploading CCC5CED2-C47F-44C9-B9F2-D3F7C153D9FD.jpeg…]()

**Comment by johnnync13** [comment]
@stevezhengshiqi any update?

**Comment by stevezhengshiqi** [comment]
Try to use this one.
[SSDT-PXSX.aml.zip](https://github.com/daliansky/XiaoMi-Pro/files/2714534/SSDT-PXSX.aml.zip)

**Comment by johnnync13** [comment]
thank you very much! I'm trying to do pci-list now
