### ISSUE TITLE
Headphone doesn't work properly

### ISSUE THREAD

**Issue by Alecyrus** [daliansky/XiaoMi-Pro#124]
I installed macOS Mojave on my MI-pro(i7 version) by adding a PM961 SSD. And I found the headphone  does not work. Once I plug the headphone in, I heard some strange sound, like electricity mixed some noise rather than the music I expect.  I notice the "ALC Plug Fix", but I am not sure it is for the issue I met. Anyone help ?

**Comment by Alecyrus** [comment]
@daliansky @stevezhengshiqi

**Comment by stevezhengshiqi** [comment]
Yes, please try.

**Comment by Alecyrus** [comment]
It works.. Thanks.:smile:
