### ISSUE TITLE
latest voodooi2c commits.

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro#126]
Can someone build latest voodooi2c commits ? Tried myself but didn't succeeded.
Seems that scaling issue is fixed.

**Comment by stevezhengshiqi** [comment]
Actually, the version in this GitHub already fixed the scaling issue. 
Anyway, I will update kexts later. Waiting for university applications these days.

**Comment by Mateo1234454545** [comment]
Thank you again for all your great work.

**Comment by stevezhengshiqi** [comment]
You're welcome. I think next time you can ask your questions in https://www.tonymacx86.com/forums/mojave-laptop-support.196/ or https://www.insanelymac.com/forum/ and wait for professional help. This issue page is specific for XiaomiPro's after-installation issues.
