### ISSUE TITLE
ALCPlugFix how to figure the hda-verb needed to pass

### ISSUE THREAD

**Issue by sakoula** [daliansky/XiaoMi-Pro#134]
Hi again! 

I am having the XiaoMi-Air-2016 and I am trying to figure out the ALCPlugFix. How do you figure out which hda-verb to pass when for the ALCPlugFix? My audio controller is the ALC255.

Thanks!

**Comment by stevezhengshiqi** [comment]
Hi, ALCPlugFix is a general fix for almost all the Realtek sound cards. Maybe you need to check your model's codec information is correct or not in https://github.com/RehabMan/EAPD-Codec-Commander.

**Comment by stevezhengshiqi** [comment]
After some learning, I notice that you need to copy the codec commands for your specific audio model from https://github.com/RehabMan/EAPD-Codec-Commander to https://github.com/goodwin/ALCPlugFix/blob/master/ALCPlugFix/main.m#L109 and build your own ALCPlugFix.

Or you can generate the codec command by following the instruction in [Any fix to the Garbled/Distorted Headphone issue?](https://www.tonymacx86.com/threads/any-fix-to-the-garbled-distorted-headphone-issue.159031/page-3)
