### ISSUE TITLE
Loaded devices

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro#135]
Is it possible to check if macbook pro 14,1 or 14,2 have loaded smbus and lpc at ioreg?
Cause I read somewhere that these methods are not used anymore with newer systems.
Thank you again.

**Comment by stevezhengshiqi** [comment]
Hi, thank you for pulling issues. I recommend you to check it by yourself(probably borrow a friend's MacBookPro or go to Apple Store) to verify your guess. And also please put the reference link of what you read to help us tracking the source.

By the way, I have already looked several MacBookPro14,1 and MacBookPro14,2's ioregs and they do not load AppleLPC and AppleSMBUS, so this repository do not provide SSDTs to fake these kinds of device.

**Comment by Mateo1234454545** [comment]
Sorry to ask so many things. I'm getting close to being annoying  , am I ?
Reason I ask is because I trust your work. 
And there are not many people who know hackintosh like you. And not all of them willing to help.

Can I ask something else ? 
I have a dell 5570 laptop with alsmost same specs like xiaomi notebook , except for some things  don't work , like audio and i2c trackpad.
If you have the time , please ,could you make a clover folder for me (acpi hotpatch) like the work you did on xiaomi? 
I sent you the origin folder.
[origin.zip](https://github.com/daliansky/XiaoMi-Pro/files/2729435/origin.zip)

**Comment by stevezhengshiqi** [comment]
Thank you for your compliment. A lot of pros like Rehabman are much more knowledgeable than me.  Their awesome forums and drivers help a lot. 

Could you also put your CLOVER folder which you are using? Maybe it's easier for me to make changes based on the work you have done.I will check it if I am free.

**Comment by Mateo1234454545** [comment]
Here you are. 

What I've done till now is make audio work (but sometimes is lost after sleep) and cpu/gpu proper management (I use macbook pro 15,2 cause it is more suitable for kabylake-r , in my opinion).

What I need , with your help , is proper acpi hotpatch for my system and working i2c trackpad.
And everything else you could optimise/change.

Thank you again.

[CLOVER.zip](https://github.com/daliansky/XiaoMi-Pro/files/2729449/CLOVER.zip)

**Comment by Mateo1234454545** [comment]
Just a reminder.

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 Sorry for delay. I am busy for schools these days. For I2C trackpad, the official instruction is at https://voodooi2c.github.io/#GPIO%20Pinning/GPIO%20Pinning. Official chat room is a t https://gitter.im/alexandred/VoodooI2C. You can ask for the author([alexandred](https://github.com/alexandred/VoodooI2C)) for professional help.

I need an ioreg with VoodooI2C+VoodooI2CHID installed to check the `IOInterruptSpecifiers` according to Step 1 in [instruction](https://voodooi2c.github.io/#GPIO%20Pinning/GPIO%20Pinning).

**Comment by Mateo1234454545** [comment]
[5570.ioreg.zip](https://github.com/daliansky/XiaoMi-Pro/files/2758067/5570.ioreg.zip)
Here you are.
Take your time. Your school comes first.

**Comment by stevezhengshiqi** [comment]
Try this. I'm not sure whether it works.
[CLOVER.zip](https://github.com/daliansky/XiaoMi-Pro/files/2758663/CLOVER.zip)

**Comment by Mateo1234454545** [comment]
Working great !!!
I was hoping for acpi hotpatch , but I know that is a lot of work.
Thank you.

**Comment by Mateo1234454545** [comment]
Wow !!!
As far I can see it is working great.

**Comment by Mateo1234454545** [comment]
After 4days everything still working great!! Thank you for all the work.
Can I ask something ?

1) How did you manage to get i2c trackpad working without a ssdt for it? In config.plist I see 2 patches : change MATH._STA and LDR2._STA to XSTA , and change SDM0 == Zero to SDM0 > Zero.
Are these the ones required for i2c?

2) At your xiaomi-pro repo , I see acpi hotpathes like dmac and mem2. Do I need them ?

3) When you find the time again , is it possible to help me get HIDPI at 1680x944 ? At my laptop there are no glitches  at all. I'm trying to built it , I follow every guide (including one-key-hidpi and new hackintool) , I do get 1680x944 analysis but there is no HIDPI.

Thank you once again.

**Comment by Mateo1234454545** [comment]
@FallenChromium , please read more carefully.
I'm not talking about xiaomi pro.

**Comment by FallenChromium** [comment]
@Mateo1234454545 I know you're telling about DELL laptop, but you asked about why touchpad is working without patches, and I answered your question.

**Comment by Mateo1234454545** [comment]
Mine wasn't working without ssdt.
But @stevezhengshiqi somehow did it.

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 1. change SDM0 == Zero to SDM0 > Zero patch and SSDT-XOSI are needed for your trackpad. Do you need more information about the patch? It's mainly to let `_CRS` method in your TPD0 device return `(SBFB,SBFG)`

2. Real MacBookPros have DMAC and MEM2 devices, but hackintosh works fine without them.

3. I need your device-id and vendor-id of your monitor.
`ioreg -l | grep "DisplayVendorID"
ioreg -l | grep "DisplayProductID"`

Hacks are about endless try and gaining sense of accomplishment. Follow the instructions givens by pros and you can make it!

**Comment by Mateo1234454545** [comment]
1. Got it. I knew about crs patch. I've never seen it in such form though.
3. "DisplayVendorID" = 2533  ,  "DisplayProductID" = 1705.
     Attaching my EDID in case you need it , too.

[Unknown Monitor.txt](https://github.com/daliansky/XiaoMi-Pro/files/2777618/Unknown.Monitor.txt)

**Comment by Mateo1234454545** [comment]
1) There is an option to select 1680x944 , but it is not HIDPI. In fact I can select the opposite , 840x742 HIDPI which looks like 1680x944 , but of course fonts are way too big.
It is not your fault , same thing happens with one-key-hidpi. Maybe something changed at latest versions of HS and Mojave.
<img width="840" alt="untitled" src="https://user-images.githubusercontent.com/42322772/51459809-5d403400-1d62-11e9-874d-d18bd4cbad07.png">
![untitled2](https://user-images.githubusercontent.com/42322772/51459810-5dd8ca80-1d62-11e9-8399-a99fe5606d9a.png)

2) Can I ask something else ? Do you recommend ipic and hpet and rtc fix at config.plist as @Rehabman suggests ?

**Comment by stevezhengshiqi** [comment]
1. But Xiaomi-Pro can actually use 1680x944 hidpi, maybe we need further configuration for your device.

2. It depends on you, actually. If you meet problems as [written by Rehabman](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_HD615_620_630_640_650.plist) about `onboard audio/USB/etc`, you may need these fixes. What I did for Xiaomi-Pro is to emulate a real MacBookPro14,1 as far as I can.

BTW, I notice that your device-id is `19160000`, which may not perfectly with `Intel UHD 620` according to [SSDT-IGPU](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-IGPU.dsl), 
` // Kaby Lake-R/UHD620
            0x5917, 0, Package()
            {
                "AAPL,ig-platform-id", Buffer() { 0x00, 0x00, 0x16, 0x59 },
                "hda-gfx", Buffer() { "onboard-1" },
                "model", Buffer() { "Intel UHD Graphics 620" },
                "device-id", Buffer() { 0x16, 0x59, 0x00, 0x00 },
            },
`
`59160000` is recommended.

**Comment by Mateo1234454545** [comment]
1) I can use 1920x1080 HIDPI , 1440x710 HIDPI but not 168x944.

I changed it recently. I was using 5916 but there were some glitches with some videos and especialy HDMI. With spoofing skylake 1916 (needs lilupcu=8) things are better. And power management , too. Maybe you give it a try.
