### ISSUE TITLE
iMessage的使用

### ISSUE THREAD

**Issue by xl-jack** [daliansky/XiaoMi-Pro#138]
请教一下小米笔记本 pro high sierra 13.6 的 iMessage 能不能使用？有没有详细教程？

**Comment by stevezhengshiqi** [comment]
你好，这个问题不太属于本仓库讨论的范畴。个人推荐阅读https://forum.51nb.com/thread-1757464-1-1.html 或者 https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/。 比较完美的方案是用`iMessageDebug` 获取白果的三码然后填入 `config.plist` 里。
