### ISSUE TITLE
Touchpad won't work with last version

### ISSUE THREAD

**Issue by Noitham** [daliansky/XiaoMi-Pro#14]
I applied the CLOVER folder, and after that, the touchpad stopped moving... had to format and reinstall with the clover given here:
(v0.5)
https://www.tonymacx86.com/threads/guide-xiaomi-mi-notebook-pro-high-sierra-10-13-3.242724/

**Comment by stevezhengshiqi** [comment]
Try to run Kext Utility and restart. The reason may the system I2C kexts are not disabled completely, which makes the VoodoI2C not work.

**Comment by sshilko** [comment]
Xiaomi Mi Book Air 2018 (i7 8gen) keyboard and trackpad not working, using usb external ones.
Used original guide and replaced wit clover 0.5, still didnt work :(

**Comment by stevezhengshiqi** [comment]
@sshilko Although Xiaomi Mi Book Air 2018 (i7 8gen) uses mostly the same hardware as Mi Pro, some functions are not working well. For keyboard, I recommend to use Rehabman's VoodooPS2Controller: https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller. For trackpad, it seems like you have to patch DSDT to make VoodooI2C work: https://voodooi2c.github.io/#GPIO%20Pinning/GPIO%20Pinning
