### ISSUE TITLE
iMessage and FaceTime not working

### ISSUE THREAD

**Issue by FlavortownFieri** [daliansky/XiaoMi-Pro#141]
I have managed to tweek a few things and make it possible to log into my general icloud account however when I try to login with that same account on iMessage or Facetime it tells me that "You cannot sign into FaceTime/iMessage on this mac at this time" any ideas?

**Comment by Menchen** [comment]
Did you change your serial number in clover? If no not go change it and follow the guide in tonymac..

**Comment by stevezhengshiqi** [comment]
Agree. Please read instruction at https://www.tonymacx86.com/threads/how-to-fix-imessage .This issue is identical to [#138](https://github.com/daliansky/XiaoMi-Pro/issues/138).

**Comment by smellord** [comment]
I suppose it won't work because of the eth0. I'm using usb tethering through an android phone and I can't set the interface to eth0.

**Comment by stevezhengshiqi** [comment]
@smellord NullEthernet.kext will fake an ethernet device to en0, so don’t worry about en0. The reason why iMessage doesn’t work is because of serial number and can be fixed if follow the instruction.

**Comment by stevezhengshiqi** [comment]
Move to https://github.com/daliansky/XiaoMi-Pro/issues/152
