### ISSUE TITLE
updated to 10.14.3 touchpad not working

### ISSUE THREAD

**Issue by artemis77799** [daliansky/XiaoMi-Pro#144]
i just updated to 10.14.3 and touch pad stopped working, idk what to do

**Comment by Menchen** [comment]
You need rebuild kext cache every update.. read readme about how to do it.

**Comment by artemis77799** [comment]
sorry didn't noticed that in the readme, thanks it worked

**Comment by artemis77799** [comment]
ps: do you have a guide to add the wifi/bt card in the m2 slot? i saw some posts on this GitHub but never found a guide, i'm pretty unxeperienced

**Comment by Menchen** [comment]
The wifi part shuold be easy, open up the case with T5 screwdriver and pull battery off. Insert the card at right side and secure... for bt you need soldering it to wla pin 4 and 5. You can check it at repo under steve name(not this,)under a closed issue.
