### ISSUE TITLE
外置 USB 蓝牙怎么解决？

### ISSUE THREAD

**Issue by huangdongjie** [daliansky/XiaoMi-Pro#146]
我用的是 13.3 寸 6200u 无指纹版本的小米air，在 miui 论坛上装了个 10.12.3 的系统，想使用外置的 usb 蓝牙，但是在偏好设置里还能看到蓝牙的图标，也就是没有屏蔽笔记本自带的蓝牙，听说这就需要屏蔽内置的蓝牙才行，但是没有找到具体的解决方案，我觉得这种问题对你们来说应该挺简单的所以来问一下，希望不吝赐教。

**Comment by stevezhengshiqi** [comment]
你好，可以阅读兵哥写的教程http://bbs.pcbeta.com/viewthread-1794948-1-1.html 定制USB来禁用自带蓝牙。链接里含视频教学网址。
