### ISSUE TITLE
一個由合蓋長時間睡眠引發的引導問題

### ISSUE THREAD

**Issue by JimmyJimmyChan** [daliansky/XiaoMi-Pro#148]
stevezhengshiqi 您好：
我的小米筆記本 Pro 安裝了10.14.3，使用的 EFI 版本為 XiaoMi NoteBook Pro EFI v1.2.9，合上蓋子進入睡眠較長時間（超過4小時）後，開蓋發覺已自動關機，此時按開機按鈕並不會進入 Clover，而是自動進入 Windows，進入 BIOS 查看發覺引導順序被自動更改，Windows 變第一位， Clover 變第二位，連續測試了兩次合蓋長時間休眠都是如此，請問這個問題需要如何修正呢？如能解答，感激不盡，非常感謝您的 EFI 貢獻。

**Comment by FallenChromium** [comment]
I can say that same happened to me, looks like Hibernate playing with NVRAM, which makes sense on Apple laptops but not on our - it changes boot order to drive, but in my case Clover is under /EFI/ubuntu/GRUBX64.efi, so I'm getting booted in Windows. I think that disabling hibernation should fix that, but it's not the fix I'd be fine with 😂

**Comment by JimmyJimmyChan** [comment]
> I can say that same happened to me, looks like Hibernate playing with NVRAM, which makes sense on Apple laptops but not on our - it changes boot order to drive, but in my case Clover is under /EFI/ubuntu/GRUBX64.efi, so I'm getting booted in Windows. I think that disabling hibernation should fix that, but it's not the fix I'd be fine with 😂

It seems that this is not an example, then we can only temporarily disable the Hibernate, and wait for the author to update the sleep method. My English level is very general, so I translated Chinese into English through Google Translate, please forgive me. 😂

**Comment by stevezhengshiqi** [comment]
@JimmyJimmyChan 妳好，可以提供壹下妳正在使用的CLOVER文件夾嗎？我猜測妳的問題可能是由RTC導致的CMOS時鐘重置，我試試去掉HibernationFixup和相關慘數，然後發給妳再測試。還有壹個問題：妳的機子是GTX版嗎？
By the way, your English is good enough, don't worry about that.

Related issue: https://github.com/daliansky/XiaoMi-Pro/issues/109.

**Comment by JimmyJimmyChan** [comment]
> @JimmyJimmyChan 妳好，可以提供壹下妳正在使用的CLOVER文件夾嗎？我猜測妳的問題可能是由RTC導致的CMOS時鐘重置，我試試去掉HibernationFixup和相關慘數，然後發給妳再測試。還有壹個問題：妳的機子是GTX版嗎？
> By the way, your English expression is good, don't worry about that.
> 
> Related issue: #109.

@stevezhengshiqi 您好：

Clover 文件夾已上傳，請查看；我的小米筆記本 Pro 非 GTX 版，而是初始發行的 MX150 版。
[Jimmy - Clover.zip](https://github.com/daliansky/XiaoMi-Pro/files/2818581/Jimmy.-.Clover.zip)

除此之外，我有以下兩個新的問題：
1. 目前開機進入 Clover 選擇 macOS 有一定概率會在讀條介面很快黑屏重啟，需要 -v 才能進入系統，安裝系統後我曾使用過通用的開啟 HIDPI 教程，但很快將其卸載，換成您提供的專用開啟 HIDPI 文件與步驟，不知是否因此影響到開機？
2. 觸控板能否實現「雙指連續輕點兩下後不放手即可拖動窗口／文件」？我在系統的觸控板設置中沒有找到相關的選項。

感謝您的回覆與鼓勵！

**Comment by stevezhengshiqi** [comment]
@JimmyJimmyChan 不用這麽客氣啦。
1. 應該和HIDPI無關，跟EFI有比較大的關系，可能是驅動沖突，看看我給妳的這個能不能順便解決。
2.這個在系統偏好設置-輔助功能-觸控板-觸控板選項-拖移鎖定自行設置，相信網上有更詳細的教程。
[Jimmy - Clover 1.zip](https://github.com/daliansky/XiaoMi-Pro/files/2822789/Jimmy.-.Clover.1.zip)

**Comment by JimmyJimmyChan** [comment]
@stevezhengshiqi 
Hello，我已替換您最新提供的 EFI 文件夾，經過一天測試的情況如下：

1. 長時間合蓋睡眠不再自動關機，開蓋即可正常進入 macOS 的解鎖介面，接下來我將就這點測試續航，看看深度睡眠期間的電池控制是否能夠與真正的 Macbook Pro 一致（極少的耗電量）；
2. 關機後開機 / 重新開機 這兩項操作均正常，不再黑屏自動重啟；
3. 觸控板已設置好，與 Windows 操作一致。

Thank you very much!

**Comment by stevezhengshiqi** [comment]
@JimmyJimmyChan 很高興妳的休眠和開機重啟問題得到緩解。可以幫助我再測試下這個EFI嗎，這個EFI只刪除了 `CPUFriend*`。
第壹個給妳的EFI刪除了`HibernationFixup`, `CPUFriend*`，並且在config裏勾選了`NeverHibernate`。我不太確定到底是Hibernation相關驅動還是CPUFriend導致了妳的異常。 `HibernationFixup` 可以讓睡眠更貼近白果，如果是因為它引起的問題那就太可惜了

**Comment by JimmyJimmyChan** [comment]
> @JimmyJimmyChan 很高興妳的休眠和開機重啟問題得到緩解。可以幫助我再測試下這個EFI嗎，這個EFI只刪除了 `CPUFriend*`。
> 第壹個給妳的EFI刪除了`HibernationFixup`, `CPUFriend*`，並且在config裏勾選了`NeverHibernate`。我不太確定到底是Hibernation相關驅動還是CPUFriend導致了妳的異常。 `HibernationFixup` 可以讓睡眠更貼近白果，如果是因為它引起的問題那就太可惜了。
> [Jimmy - Clover 2.zip](https://github.com/daliansky/XiaoMi-Pro/files/2825556/Jimmy.-.Clover.2.zip)

@stevezhengshiqi 好的，我現在下載替換測試，明天給您測試結果。

**Comment by JimmyJimmyChan** [comment]
@stevezhengshiqi 
經過測試，合蓋10小時後開蓋再次復現了之前的問題；
從 Google 得知有三個變量影響睡眠後的最終效果：
1. `EmuVariableUefi-64.efi`（[參考鏈接](https://www.cnblogs.com/motoyang/p/6075973.html)）
2. 在終端中手動切換睡眠模式（上面的參考鏈接中有提到）
3. `config.plist` 中的 `NeverHibernate` 選項
4. `HibernationFixup.kext`

目前我不敢去除 `NeverHibernate` 選項的勾選，因為我害怕開機後硬盤進入加密模式而無法進入系統（上面的參考鏈接中有提到），所以我暫時不知道該如何用排除法徹底解決問題來源，請問有什麼好建議嗎？

**Comment by stevezhengshiqi** [comment]
`EmuVariableUefi-64.efi` 和本EFI無關，它適用於不支持nvram的BIOS。
加密指的是休眠後系統對工作中的進程和文件的加密，喚醒自動解密，不存在無法進入系統。我覺得是RTC引起的休眠問題，試試這個EFI。
[Jimmy - Clover 3.zip](https://github.com/daliansky/XiaoMi-Pro/files/2828124/Jimmy.-.Clover.3.zip)

**Comment by JimmyJimmyChan** [comment]
@stevezhengshiqi 
Hello，換上 Clover 3 之後，目前問題依然存在。
Happy New Year in 2019!

**Comment by JimmyJimmyChan** [comment]
@stevezhengshiqi 
Hello，上面更新的兩個 Clover 都無法長時間合蓋休眠，我在配置介面中自行去除了 RtcHibernateAware 和 HibernationFixup 的勾選，可以合蓋休眠，但續航無法像 Macbook 一樣省電，合蓋8小時後少了10%左右。

**Comment by stevezhengshiqi** [comment]
嗯，嘗試勾上HibernationFixup+AppleRTC，kexts/Other目錄放回HibernationFixup，移除RtcHibernateAware。

**Comment by stevezhengshiqi** [comment]
已在v1.3.1用了 `NeverHibernate` 並移除了 `RtcHibernateAware`。

**Comment by orditeck** [comment]
@JimmyJimmyChan I have a similar problem, see #109. I haven't thought about looking at the BIOS boot order after having the issue, I'm sure I'd have the same problem too (boot order changed). It makes so much sense.

My question is: do you have MacOS&Windows installed on the SAME drive or do you have one SSD for MacOS and one SSD for Windows? I personally have two SSD and would like to check if the problem only happens with two disks as on my issue, someone with one disk & two OS on it said he has no problem. 

I should just try to remove my Windows SSD as I haven't used Windows for months, it could be a good thing to try.

**Comment by stevezhengshiqi** [comment]
Mark as solved, feel free to reopen this issue if not.
