### ISSUE TITLE
Main screen black when another screen is plug in HDMI

### ISSUE THREAD

**Issue by Vichearith** [daliansky/XiaoMi-Pro#149]
The main screen from the Xiaomi is black when the computer is plugged to another screen. It displays everything find before the authentification page so Clover / EFI seems OK. It happends most of the time but sometime, it works fine, the 2 screens displays what they should

**Comment by stevezhengshiqi** [comment]
Hi, please read `README` carefully. You may need to close the lid for five seconds and reopen it after plugging the external screen.
`Use HDMI port on the left side may cause black internal display, please try to reopen the lid.`

**Comment by Vichearith** [comment]
Ty !

**Comment by sgimmai** [comment]
Is there a way to improve this workaround? Which file(s) needs tweaking?
I will try to have a look and try to fix it - if possible.

**Comment by stevezhengshiqi** [comment]
@sgimmai It seems fixed in https://github.com/acidanthera/WhateverGreen/commit/8689a5c872b19319b0039868d352967cd3c1b589. Check the document.

**Comment by MarFre22** [comment]
In order to improved and organize the project with all valuable changes, like this topic and the hibernation on the 10.14.5 and others, Is it possible to make a new stable version of EFI folder?

**Comment by stevezhengshiqi** [comment]
@MarFre22 No problem. I am planning to 
 - wait and include [Acidanthera](https://github.com/acidanthera?tab=repositories)'s official releases of Lilu and its plugins
 - merge [VoodooI2C Fix](https://github.com/alexandred/VoodooI2C/pull/195)
 - attempt to fix 10.14.5 Hibernation from https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/197#issuecomment-504806858
 - play around with `-igfxhdmidivs` and `-igfxlspcon` boot argument to fix HDMI black screen

Recently I have many classes, and I will try to get theses things done quickly.

**Comment by MarFre22** [comment]
@stevezhengshiqi Thank you very much for helping. Also thanks for helping intensively this project!!! And good luck for the classes!!
