### ISSUE TITLE
关于空闲时CPU频率较高造成耗电问题

### ISSUE THREAD

**Issue by chewenkai** [daliansky/XiaoMi-Pro#15]
**首先感谢@daliansky做的工作** 
---
### 问题
我的小米笔记本Pro 16G 版本 之前一直使用的是Arch Linux，CPU频率在空闲时是800Mhz，一般开大型IDE写个代码能写5-6个小时。
顺利安装了MacOS以后，使用HWMonitor软件发现频率一直居高不下，空闲时也在1.29Ghz，现在电量基本上2-3个小时就耗尽了。

希望能帮忙解决，感谢🙏

PS：使用的是最新的EFI

**Comment by chewenkai** [comment]
参考博客[如何检查CPU的Speedstep是否生效](http://www.yekki.me/how-to-verify-cpu-speedstep/)发现SpeedStep好像没有打开。
我的输出信息是：
```
默认	15:36:06.238208 +0800	kernel	AICPUPMI: CPU P-States [
默认	15:36:09.243251 +0800	kernel	AICPUPMI: CPU P-States [
默认	15:36:13.748764 +0800	kernel	AICPUPMI: CPU P-States [
默认	15:36:24.267941 +0800	kernel	AICPUPMI: CPU P-States [
默认	15:36:33.283737 +0800	kernel	AICPUPMI: CPU P-States [

```

**Comment by chewenkai** [comment]
再啰嗦一下😨

发现一个跟本问题很相似的问题[链接](http://bbs.pcbeta.com/viewthread-1670946-1-6.html)。根据其方法寻找到了**MacbookPro14,1**对应的plist文件**Mac-B4831CEBD52A0C4C.plist**，但是打开后里面的频率不是数字的形式。

用[脚本](https://github.com/Piker-Alpha/freqVectorsEdit.sh)修改该文件的最低CPU频率，按照说明修改成功后，测试发现最低频率并没有下降。

**Comment by daliansky** [comment]
看来你是没有找到小米PRO的黑苹果高级群，群里有很多个测试版本的EFI，里面已经包含了CPU变频的驱动，其实就是SMBIOS设置为MBP14,1，然后打开HWP

**Comment by chewenkai** [comment]
谢谢，已经可以了。

**Comment by feiweiwei** [comment]
> 谢谢，已经可以了。测试频率可以下降。
你好，我也是16g的pro，你是怎么解决的？用的哪个附件，我看有好几个，不知道该用哪个，谢谢。

**Comment by stevezhengshiqi** [comment]
@feiweiwei 更换成最新v1.2.8 release就可以了。
