### ISSUE TITLE
Notices about plygintype=true.

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro#153]
@stevezhengshiqi  , Since we have almost the same hardware (Dell 5570 with i5-8250u and Intel 620) , here are some notices about HWP capabilitites.
If I use plygintype=true, I have HWP enabled but there are 2 problems : 
a) Battery percentage is 5-6% off compared to coconutbattery and bios , and
b) getting errors like : 
"2019-02-08 21:01:41.399863+0200  localhost kernel[0]: (kernel) VoodooI2CControllerDriver::pci8086,9d60 Warning: Error getting bus config, using defaults where necessary
2019-02-08 21:01:44.767156+0200  localhost kernel[0]: (AppleIntelKBLGraphicsFramebuffer) <AppleIntelKBLGraphicsFramebuffer`AppleIntelFramebuffer::getAttribute(unsigned int, unsigned long*)> [IGFB][ERROR  ] getAttribute called when FB0 is in a sleep state - attribute: 'gnps'
2019-02-08 21:01:44.767238+0200  localhost kernel[0]: (AppleIntelKBLGraphicsFramebuffer) <AppleIntelKBLGraphicsFramebuffer`AppleIntelFramebuffer::setAttribute(unsigned int, unsigned long)> [IGFB][ERROR  ] setAttribute called when FB0 is in a sleep state - attribute: ' par'".

 So , i disabled plygintrue and now I don't have HWP enabled but : 
a) battery percentage is accurate.
b) there are no errors like above.
c) cpu idles at 1ghz instead of 1,2ghz before  (I don't use any cpufriend at both cases).
d) system feels more responsive (maybe it is a placebo)
e) getting better speeds with geekbench , and the most imprortant 
f) battery doesn't seem worse either. In fact seems a lttle more better , but I need to confirm this over time.

If anyone is  interested give it a try.

**Comment by stevezhengshiqi** [comment]
It's the same as `plugintype=1`.

**Comment by Mateo1234454545** [comment]
> It's the same as `plugintype=1`.

You were faster than my notice.

**Comment by stevezhengshiqi** [comment]
You have really great thoughts. However, I may still resist to use `plugintype=1` for following reasons:
a) Factors that affect battery can be various.
b) For that VoodooI2C error, it's a common error flag for almost every VoodooI2C user.
For the IGFB error, that's also a common error for even real MacBookPros. 
![img_0804](https://user-images.githubusercontent.com/36894554/52504226-be04b300-2c22-11e9-8efe-c4589d7e6e3e.JPG)
I don't think that eliminating these errors will actually bring benefits to our devices. 

c) Most importantly, in MacBookPro14,2's CpuSsdt, `plugintype=1` is also injected. I believe Apple does this for a reason, maybe match X86PluginType.kext, and it's better to follow Apple's standard by imitating their ACPI grammar.
[System SSDT-10.dsl.zip](https://github.com/daliansky/XiaoMi-Pro/files/2846750/System.SSDT-10.dsl.zip)

Higher Geekbench score may not reflect that the CPU is running more efficiently. Without HWP, the CPU may handle multiple processes inefficiently and have unexpected temperate/utilization/frequency curves from OEM vendors' design.
