### ISSUE TITLE
trackpad is disabled when internal keyboard is in use

### ISSUE THREAD

**Issue by bamdadkhan** [daliansky/XiaoMi-Pro#155]
hi,

the trackpad switches off for approx. 250 milliseconds when typing something. this makes dragging/pointing and command-tabbing difficult. is there a .plist i can edit to disable this behaviour?

cheers,
bamdad

**Comment by Menchen** [comment]
See readme and #19

**Comment by stevezhengshiqi** [comment]
Duplicate issue, and I will close it.

**Comment by bamdadkhan** [comment]
sorry about that and thanks.
