### ISSUE TITLE
小米 Air 2018 无法调节亮度（Can't adjust the brightness on Xiaomi Air 2018）

### ISSUE THREAD

**Issue by vimcaw** [daliansky/XiaoMi-Pro#158]
非常感谢各位贡献者对这个项目的付出 👏。

我的电脑是`小米 Air 2018 13.3'`，CPU 是 `i7 8550U`，看了配置基本和小米 Pro一模一样就用了这个。

其他都没问题，就是发现调节不了亮度，快捷键（F4、F5 对应的功能键）无反应，我尝试用 `Karabiner-EventViewer` 录制键值，但是按下这两个按键时没有记录下任何键值。

而且系统偏好设置里的“显示器”项目也没有亮度调节条，但是显卡又是一样的，请问下这种情况我该如何解决？

------
English Translation:

Thanks for all contributor's work 👏

My device is `Xiaomi Air 2018 13.3'`, the CPU is `i7 8550U` and I found many parameters are same, so I used this EFI.

Anything works well except the function key. Brightness key (F4, F5 corresponding function keys)  doesn't work. I tried to record the key assignments with `Karabiner-EventViewer`, but did not record any key assignments when I pressed the two keys.

And the "Monitor" item in the system preferences does not have a brightness adjustment bar, but the graphics card is the same. How can I solve this situation?

**Comment by johnnync13** [comment]
@vimcaw https://github.com/johnnync13/Xiaomi-Mi-Air

**Comment by vimcaw** [comment]
@johnnync13 Thank you for great work, it works perfectly.
