### ISSUE TITLE
Enabling dGPU for GTX version 

### ISSUE THREAD

**Issue by TobiasBouma** [daliansky/XiaoMi-Pro#159]
Hi and sorry for my noob question previously. Your message indeed solved the problem. The below is not so much an issue but I can imagine it will be useful to a larger group of future users of your hack:

I'd like to use my 1050 gtx from the GTX version of the notebook pro.  The dedicated Gpu is disabled by your current SSDT-DDGPU aml file. How does one go about enabling this? I have nvram working and nvidia cuda + Web drivers installed. 

Is it satisfactory to remove the patched file? I could not find an original ssdt ddgpu from the Web... 

Cheers

PS I am aware there is no out of the box support for the GTX version as mentioned in readme. If it is definitely outside the scope of your interests feel free to bin this request.

**Comment by Menchen** [comment]
Optimus (the mechanism to switch dgpu to igpu and vice versa) is not supported in hackintosh yet(probably never as macbook use other mechanism) so if you want or need Nvidia gpu, you need go to windows or linux... (and even we can drive it, it would be better to run game on windows.. if game is a must. )

**Comment by stevezhengshiqi** [comment]
Agree. As I said in README, Optimus laptop’s discrete card aren’t be supported by macOS, and currently there’s no solution.

It’s better to disable the discrete card to save power.

Ref: https://www.tonymacx86.com/threads/guide-disabling-discrete-graphics-in-dual-gpu-laptops.163772/

**Comment by TobiasBouma** [comment]
Thanks for your quick messages. 

I also stumbled upon this last thread which disables rather than enables the dgpu. 

I am interested in using only the dgpu. How would I enable this given the daliansky config?

**Comment by stevezhengshiqi** [comment]
There’s actually no way to let macOS support our discrete card. Delete SSDT-DDGPU only results in power hungry. 

macOS can’t support Optimus tech. You could google mac+optimus for more information.

**Comment by TobiasBouma** [comment]
I'm confused.

Nvidia released drivers for my card,  a 1050 gtx.  Why will this card not
work? If I install the drivers and set this gpu as my primary gpu, how can
this fail?

Enabling or using optimus is not the goal here,  I'm OK with having a power
hungry setup with 1050 as gpu and a separate boot profile for desktop
work.  This circumvents the need for optimus, does it not?

**Comment by stevezhengshiqi** [comment]
Please google `macOS+Optimus` for more information. I said many times: macOS doesn't support Optimus laptop. Because we use Optimus, the discrete card can never be set to the primary gpu and macOS can never drive it.
Optimus tech is embedded in BIOS and is enabled all the time.
