### ISSUE TITLE
大佬们能不能写一个登陆appstore的教程，内建网卡的mac也改了，还是登不上，500错误

### ISSUE THREAD

**Issue by ShaoGongBra** [daliansky/XiaoMi-Pro#160]

**Comment by vimcaw** [comment]
具体是什么错误内容？有截图吗？

**Comment by ShaoGongBra** [comment]
淘宝找人操作，似乎是运行了这个串代码之后就能登录了，因为他的其他操作似乎都和我的一样
`defaults write com.apple.appstore.commerce Storefront -string "$(defaults read com.apple.appstore.commerce Storefront | sed s/,8/,13/)"`
