### ISSUE TITLE
帧缓存修复 备份脚本Error 318

### ISSUE THREAD

**Issue by brady2037** [daliansky/XiaoMi-Pro#163]
Intel (R) Flash Programming Tool. Version:  11.6.29.3287
Copyright (c) 2007 - 2017, Intel Corporation. All rights reserved.

Reading HSFSTS register... Flash Descriptor: Valid

        --- Flash Devices Found ---
        MX25L6473E      ID:0xC22017     Size: 8192KB (65536Kb)

Error 318: The host CPU does not have read access to the target flash area. To enable read access for this operation you must modify the descriptor settings to give host access to this region.
FPT Operation Failed.

**Comment by brady2037** [comment]
DVMT_and_0xE2_fix 下 Backup.cmd

**Comment by brady2037** [comment]
Power Shell内容
PS C:\Windows\system32> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    Undefined
   UserPolicy        Undefined
      Process         Undefined
  CurrentUser      Unrestricted
 LocalMachine    Unrestricted

**Comment by brady2037** [comment]
参考：http://zgserver.com/powershell-18.html
更改本地组执行策略 后还是不行

**Comment by Menchen** [comment]
要用 usb 启动 bios 更新。 然后运行 unlock.nsh (类似名字。)

**Comment by brady2037** [comment]
> 要用 usb 启动 bios 更新。 然后运行 unlock.nsh (类似名字。)

是指usb启动在PE系统中运行脚本吗

**Comment by Menchen** [comment]
@brady2037 是这个 https://yadi.sk/d/uJBj8pp7wXMR-g  (603 的,不过只用unlock应该没事), 这个 repo 里面的是在windows里面的, 你把这个下载了然后格式化 u盘到 FAT16 然后直接拉进去然后到F12 UEFI 启动u盘. 然后 ./unlockme.nsh 就可以了.. 还需要帮忙的话可以参考 YT https://youtu.be/he4QNY2slE0  记得一次性只能打一个 patch.

@stevezhengshiqi  把 TY 和 bios 上传到 repo 和更新 readme?

**Comment by brady2037** [comment]
> @brady2037 是这个 https://yadi.sk/d/uJBj8pp7wXMR-g (603 的,不过只用unlock应该没事), 这个 repo 里面的是在windows里面的, 你把这个下载了然后格式化 u盘到 FAT16 然后直接拉进去然后到F12 UEFI 启动u盘. 然后 ./unlockme.nsh 就可以了.. 还需要帮忙的话可以参考 YT https://youtu.be/he4QNY2slE0 记得一次性只能打一个 patch.
> 
> @stevezhengshiqi 把 TY 和 bios 上传到 repo 和更新 readme?

进入EFI后并没有像视频中自动重启，强制重启到win10下运行Backup.cmd依旧Error 318,直接运行DVMT_set.cmd是成功的
EFI后输出内容：
fs1:\> unlockme.nsh
unlckme.nsh> SendEcCmd.efi C9E D00
SendEcCommand(0x9E,0x0)

**Comment by Menchen** [comment]
efi 里面的unlock 好像成功了。 试了 windows 里面的unlock吗? 就是 PowerShell 那个。还有的是有些脚本要手动执行。。就是自己开个powershell 。

**Comment by ChenLLE** [comment]
请问楼主怎么解决的。。

**Comment by Menchen** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/163#issuecomment-472566302

看上面的链接
