### ISSUE TITLE
AppleIntelKBLGraphicsFramebuffer五国

### ISSUE THREAD

**Issue by ShaoGongBra** [daliansky/XiaoMi-Pro#164]
使用这个efi安装，启动不到安装界面，AppleIntelKBLGraphicsFramebuffer，然后重启

**Comment by stevezhengshiqi** [comment]
安装请看README里的文字和视频教程。确保BOOT和CLOVER文件夹删除再复制成最新release里的相应文件夹。
本仓库不讨论安装问题，因为很多帖子已经介绍得很详细了。

**Comment by ShaoGongBra** [comment]
哈哈，我直接把efi分区都格式化了复制进去的，还是不行的
