### ISSUE TITLE
Random Kernel Panics

### ISSUE THREAD

**Issue by spita90** [daliansky/XiaoMi-Pro#165]
Hi! First of all I would like to thank @stevezhengshiqi and @daliansky for their wonderful contribute to the Hackintosh world.

I have a problem on my XiaoMi-Pro Hackintosh, I try to explain my setup:

I have a XiaoMi Pro i7 16GB, with Samsung 970 EVO on primary SSD slot, and the original MZVLB256HAHQ moved on secondary SSD slot.

The 970 contains both Windows 10 and MacOS, and the secondary SSD is a NTFS data drive (accessed from MacOs by using Tuxera NTFS software).

I set up both OS to have the same Desktop, Documents, etc folders (which are on the secondary SSD drive).

Everything works definitely great, but randomly when I boot on MacOs, no folder appears on Desktop ( I assume it fails to access secondary SSD) and after 15/20 seconds it has a Kernel Panic and reboots (and the second time always works good).

This is what I get:

Anonymous UUID:       95561AA1-3A92-54D3-EAFE-086B3AAEB78F

Thu Mar 14 16:27:22 2019

*** Panic Report ***
panic(cpu 0 caller 0xffffff7f9025a172): nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0x16 VID/DID=0xa808144d
. FW Revision=EXD7201Q\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-387.230.1/IONVMeController.cpp:5327
Backtrace (CPU 0), Frame : Return Address
0xffffff920cc03a10 : 0xffffff800d3aeb0d 
0xffffff920cc03a60 : 0xffffff800d4e8653 
0xffffff920cc03aa0 : 0xffffff800d4da07a 
0xffffff920cc03b10 : 0xffffff800d35bca0 
0xffffff920cc03b30 : 0xffffff800d3ae527 
0xffffff920cc03c50 : 0xffffff800d3ae373 
0xffffff920cc03cc0 : 0xffffff7f9025a172 
0xffffff920cc03e20 : 0xffffff800da5e147 
0xffffff920cc03e90 : 0xffffff800da5e069 
0xffffff920cc03ec0 : 0xffffff800d3eb085 
0xffffff920cc03f40 : 0xffffff800d3eac35 
0xffffff920cc03fa0 : 0xffffff800d35b0ce 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[ABA6DFDD-AC72-3008-83FE-EF9722E66FEB]@0xffffff7f90245000->0xffffff7f90284fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[A2492141-9480-3177-BC7D-455925BB4A2E]@0xffffff7f8e511000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[5C9A453F-559B-3683-9E81-D288D13A33CE]@0xffffff7f8dc95000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[328FCBD7-8C2C-3A4A-AF92-9270C1403891]@0xffffff7f8ee00000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[9B2E7108-AA17-3998-BF41-4B1297F455E5]@0xffffff7f8e310000
            dependency: com.apple.iokit.IOReportFamily(47)[5F165AE5-F4F2-3415-857C-34F2462A730E]@0xffffff7f8ddcc000

BSD process name corresponding to current thread: kernel_task
Boot args: gfxrst=1 

Mac OS version:
18D42

Kernel version:
Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
Kernel UUID: 1970B070-E53F-3178-83F3-1B95FA340695
Kernel slide:     0x000000000d000000
Kernel text base: 0xffffff800d200000
__HIB  text base: 0xffffff800d100000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)

System uptime in nanoseconds: 53581732639
last loaded kext at 16053031275: com.apple.fileutil	18.306.12 (addr 0xffffff7f8eec0000, size 114688)
loaded kexts:
(none)

EOF
Model: MacBookPro14,1, BootROM 184.0.0.0.0, 4 processors, Intel Core i7, 1,99 GHz, 16 GB, SMC 2.43f6
Graphics: Intel UHD Graphics 620, Intel UHD Graphics 620, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR4, 2400 MHz, Samsung, -
Memory Module: BANK 1/DIMM0, 8 GB, DDR4, 2400 MHz, Samsung, -
Bluetooth: Version 6.0.10f1, 3 services, 19 devices, 1 incoming serial ports
PCI Card: Intel UHD Graphics 620, VGA-Compatible Controller, PCI-Express
PCI Card: Intel Sunrise Point-LP USB 3.0 xHCI Controller, USB eXtensible Host Controller, PCI-Express
PCI Card: Intel Sunrise Point-LP Serial IO I2C Controller #0, I2C, PCI-Express
PCI Card: Intel Sunrise Point-LP Serial IO I2C Controller #1, I2C, PCI-Express
PCI Card: Intel Sunrise Point-LP CSME HECI #1, IMEI, PCI-Express
PCI Card: Intel Sunrise Point-LP PMC, PCHPMC Controller, PCI-Express
PCI Card: Intel Sunrise Point-LP HD Audio, Audio Device, PCI-Express
PCI Card: Intel Sunrise Point-LP SMBus, System Management Bus, PCI-Express
PCI Card: Intel Sunrise Point-LP PCI Express Root Port #5, NVM Express Controller, M.2 key M
PCI Card: Intel Sunrise Point-LP PCI Express Root Port #9, NVM Express Controller, M.2 key M
PCI Card: Intel Wireless 8265, Other Network Controller, PCI-Express
USB Device: USB 3.0 Bus
USB Device: 4-Port USB 3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: 802.11n NIC
USB Device: XiaoMi USB 2.0 Webcam
USB Device: Bluetooth HCI
USB Device: 4-Port USB 2.0 Hub
USB Device: 2.4G Wireless Mouse
USB Device: USB 2.0 Hub
USB Device: Composite Device
Thunderbolt Bus: 

It is a little annoying and perhaps dangerous, so do you have an idea on what can cause that?

Thank you so much for your efforts.

Andrea Spitaleri

**Comment by stevezhengshiqi** [comment]
Hi, from the log you submit, it's a NVME problem. Please make sure there are not any data connections with PM981, and don't forget the CLOVER folder should also locate in a non-PM981 disk. 
In short, macOS should have zero connection with PM981 to make sure the system work well.

**Comment by spita90** [comment]
Hi! Thank you for the fast reply!
The Clover folder is in the 970 drive.
If I disable the PM981 drive in MacOs I will not have any user data, because those files and folders are share between the two OS (changed default Music, Documents, Desktop folders in Win to PM981, and simlink the same folders to the defaults in MacOs, so I can have same Desktop, Music, Documents on obth OS).

I dont want to lose access to those files. Of course I also need write access, so that's why I'm using Tuxera NTFS (I tried Paragon NTFS but that crashed the system every single time!).

Do you think I will solve the problem by replacing the PM981 with another 970, or do you think Tuxera NTFS could be the problem?

**Comment by spita90** [comment]
Also, I would like to point out that this is not even caused by Win Hibernating/Fast boot, cause I already disabled it.

By the way I'm testing if there are Kernel Panics disabling Tuxera Ntfs software... I will let you know any progress.

**Comment by Menchen** [comment]
Using a non native supported nvme that use third party driver that share folder with another os( may cause permission problem) is not recommended and will cause instability... the kext for pm981 is only for using it as data, and not something critical( that's why it's not supported. ).

**Comment by spita90** [comment]
In fact as I go on trying with Tuxera NTFS DISABLED I'm not yet getting any Kernel Panic (but I will let you know more proven conclusions in the next few days), so I'm starting to believe it is Tuxera to blame for KPs.
I in fact use PM981 only for data, nothing critical (@Menchen the kext you mention is already included and activated in this GitHub repo?).

Apart from that both OS are working great without any kind of permission problem or stuff like that.

I will update the situation with the test made, I think in the next few days.

**Comment by Menchen** [comment]
I was talking about https://github.com/RehabMan/patch-nvme

**Comment by spita90** [comment]
Ok, turns out the problem is not Tuxera, but the PM981 drive itself.
With Tuxera Disabled (so without write access to the secondary PM981 drive) I get KP only whenever i try to force write on that drive.
With Tuxera turned ON I have write access to PM981 secondary drive, but randomly when I boot up MacOs, after 1 minute or less I have KP (but no way to predict if it will happen).

@Menchen where should I find the mentioned RehabMan kext for PM981 which you say is only for using as data? Cause I actually use PM981 as data, and I could try to test it. By the way I will also need some detailed info on how to install that kext, since I'm a total noob about kexting Hackintosh...

**Comment by spita90** [comment]
We can say that Tuxera just enables write support but makes the KP unpredictable.
Btw I'm in Mojave

**Comment by Menchen** [comment]
Even using it as data only is not stable and can cause data loss. So the beset solution is making it a windows only disk.

**Comment by spita90** [comment]
Or to replace it with another 970 EVO I guess
