### ISSUE TITLE
Config compatibility with MX110

### ISSUE THREAD

**Issue by MaximKiselev** [daliansky/XiaoMi-Pro#167]
hi, guys. did u test this config on that model https://aliexpress.com/item/Xiaomi-15-6-Intel-Core/32917558893.html.
hardware properties 128GB SSD+1TB HDD i5/i7 NVIDIA GeForce MX110
thanks

**Comment by Menchen** [comment]
This repo won't work with non pro model, but you can use it as base to create your own.

**Comment by MaximKiselev** [comment]
@Menchen , ok, thanks. I will try.
