### ISSUE TITLE
About recent release.

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro#169]
@stevezhengshiqi , I saw that you have recently made 2 changes : 
a) Change inject kexts from yes to detect , and
b) replace ssdt-usb with usbports.

Can you explain why ?

**Comment by stevezhengshiqi** [comment]
These changes is not necessary. For the first one, I just try to keep the same as [RM's config sample](OS-X-Clover-Laptop-Config). For the second one, USBPorts can do both USB port and power injection, and it is recommended by Hackintool.

**Comment by Mateo1234454545** [comment]
Can I ask you for something else ?
First of all , sorry for the off topic, I'm using a Dell 5570 laptop but it has specs like Xiaomi Pro and I'm using your configuration with great success. So , thank you fo your great work !!!

So , I'm trying to get rid of the ssdt-xosi and osi to xosi rename. I managed to get trackpad work without it , but I'm facing trouble with the keyboard shortcuts for brightness.
Can you help me to get it work without the osi thing?
I'm attaching the SSDT-BRT6.aml which works with osi-xosi and config.plist and origin folder in case you need them.
Thank you again.
[config.plist.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/3304923/config.plist.zip)
[SSDT-BRT6.aml.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/3304925/SSDT-BRT6.aml.zip)
[origin.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/3304927/origin.zip)

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 Brightness hotkey needs ACPIDebug.kext and checking system.log when user presses Fn key. These things you need to do on your device.
 
Ref: https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/

**Comment by Mateo1234454545** [comment]
@stevezhengshiqi , the ssdt-brt6.aml works fine with osi to xosi patch.
Problem is that without the patch (I followed your latest releases where you removed it) doesn't work

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 Understood. I don't find the reason that it doesn't work by the first glance. I will check it later when I am free.

**Comment by Mateo1234454545** [comment]
Just a reminder.

Take your time.
