### ISSUE TITLE
使用ALCPlugFix插耳机没声音

### ISSUE THREAD

**Issue by yipingw** [daliansky/XiaoMi-Pro#170]
EFI版本：1.3.2
问题：完整替换EFI 1.3.2后使用ALCPlugFix文件夹下的sh脚本安装声卡fix，重启后插拔耳机无声音，外放有声音。该问题在我以前使用该fix的时候没出现过。
workaround：目前把layoutid从99改回30，耳机插拔有声音了。比较好奇，从commit message看说是为了稳定性考虑从30改回99，有什么不稳定吗？我用了好久没发现layout-id设置为30有什么问题。

**Comment by stevezhengshiqi** [comment]
layoutid 30的pinconfig是按照air来定制的，99才是按照pro来定制的。在黑果群里很多人反应id30会导致外放也失效，也发生在了我的机子上。

**Comment by yipingw** [comment]
> layoutid 30的pinconfig是按照air来定制的，99才是按照pro来定制的。在黑果群里很多人反应id30会导致外放也失效，也发生在了我的机子上。同时注意升级系统会导致老版本的alcplugfix失效。

感谢解答
