### ISSUE TITLE
Need help with disable internal bluetooth , and enable taoboo card

### ISSUE THREAD

**Issue by timewatchers** [daliansky/XiaoMi-Pro#172]
with new release EFI v1.3.2 , old usbpower.kext not works , i think need add entry to USBPorts.kext for disable internal Intel Bluetooth? and taobao bluetooth not work in fresh system

**Comment by stevezhengshiqi** [comment]
@timewatchers Hi, I have already updated all the USBPower to USBPorts in related issues and wiki. Please update^^.

**Comment by timewatchers** [comment]
@stevezhengshiqi thank you! USBPorts-SolderBT.kext solved problem
