### ISSUE TITLE
Pro gtx版加Mojave14.4 电量不显示，无声音，触摸板不能用，有解决方案吗

### ISSUE THREAD

**Issue by WhaleDev** [daliansky/XiaoMi-Pro#173]

**Comment by stevezhengshiqi** [comment]
@WhaleDev 你好，替换EFI即可，BOOT和CLOVER文件夹删除再复制成最新release的。此类基础问题不再给予回复。

**Comment by WhaleDev** [comment]
@stevezhengshiqi 尝试清除缓存过了无效，现在使用的是最新的EFI，是要换成老版本的吗，推荐哪个版本，谢谢！

**Comment by stevezhengshiqi** [comment]
终端输入sudo kextcache -i /，输出截图一下传上来看看。

**Comment by WhaleDev** [comment]
感谢！已解决，原本我是直接clone的整个项目，使用其中的EFI，现在用的是直接下载V1.3.2版本的EFI。
