### ISSUE TITLE
Trackpad issue in new EFI

### ISSUE THREAD

**Issue by loweets** [daliansky/XiaoMi-Pro#177]
之前一直在用 9-28-2018 这版EFI，很稳定，触摸板拖拽选择多行文本是正常

但是今天从10.14.3升级了10.14.4，用老版EFI无法启动了，只能升级了最新的EFI，
然后触摸板在选择多行文本时，中间会断掉，
拖拽文件时，也会因为拖拽距离长，拖拽的手指需要反复移动一次，而使当前拖拽中断

这个问题出现在需要连续拖拽时，拖拽手指必须离开触摸板然后再反复拖拽（左手一直点着左键，右手拖拽）

试过将老版EFI的触摸板驱动替换过来，但是依然没有作用，应该时其他地方的处理逻辑问题

这个问题看到前面有人提过，但是没解决：Trackpad behavior on 10.14.3   #156 

这个问题真的很影响使用，在需要精确选择多行，或者拖放保存网页连接的时候都没发愉快的使用了

请问有没有办法在9-28-2018这版基础上简单修改来支持10.14.4系统呢？
@stevezhengshiqi

**Comment by loweets** [comment]
把3个Voodoo开头的kext都替换成老版本了，这下终于可以了: )

**Comment by stevezhengshiqi** [comment]
厉害，如果有新版的VoodooI2C触控板驱动发布，可以帮忙测试一下是否解决了这个卡顿吗？
触控板源：https://github.com/alexandred/VoodooI2C/releases
作者刚刚修改了2.1.6的release，我手感有点迟钝，差异体验不出来。

**Comment by loweets** [comment]
新版还是不行，测试这个问题应该这样操作
对多行文本先按住左键，另一个指头拖动先选一小部分，然后放开拖动的指头往前换下再次拖动

就像你要把光标从屏幕左边移到右边，一次拖动不能完成就得手指放开再反复拖动下，就这这个换手产生了问题

**Comment by stevezhengshiqi** [comment]
@loweets 你好，我想回滚VoodooI2C的commit来修复这个问题，可以加我的QQ:467700484来讨论一下嘛，还是不太明白问题所在，十分感谢。

**Comment by tmbt78** [comment]
Hi,
i have a Huawei Matebook but i was having the same trackpad issue. I've solved it using your 1.2.8 commit ! thanks!  Have someone understood what is the problem on current VoodooI2C release and how to fix it ?
Thanks
Mattia

**Comment by wisper-shadow** [comment]
@stevezhengshiqi 加载了1.2.8的VoodooI2C驱动后，设置->辅助功能->鼠标与触摸板中的“有鼠标或无线触摸板时忽略内建触摸板“功能开启时，拔下外置鼠标触摸板无法启用，但是用力点按有反应。重建kextcache并不能解决这个问题。请问您遇到了这个问题吗？

**Comment by stevezhengshiqi** [comment]
@wisper-shadow 这是个VoodooI2C v2.1.4的时候的已知问题，在v2.1.5修复了。

**Comment by stevezhengshiqi** [comment]
@tmbt78 Hi, if you are interested, we can go back to the commit history to find the specific line that causes this issue.

I build a couple of VoodooI2Cs. If someone could try them one by one and report which one starts to have the drag problem, we can locate the specific code.
[VoodooI2C Nov 26,2018 852c48f.zip](https://github.com/daliansky/XiaoMi-Pro/files/3125909/VoodooI2C.Nov.26.2018.852c48f.zip)
[VoodooI2C 17 Dec, 2018 ecbd74.zip](https://github.com/daliansky/XiaoMi-Pro/files/3125910/VoodooI2C.17.Dec.2018.ecbd74.zip)
[VoodooI2C 18 Dec, 2018 33db3b9.zip](https://github.com/daliansky/XiaoMi-Pro/files/3125911/VoodooI2C.18.Dec.2018.33db3b9.zip)
[VoodooI2C 20 Dec, 2018 e9929cc.zip](https://github.com/daliansky/XiaoMi-Pro/files/3125912/VoodooI2C.20.Dec.2018.e9929cc.zip)

**Comment by tmbt78** [comment]
@stevezhengshiqi I've tried them all. None of them are working for a reason or another. 
Nov26 drag works but my trackpad bottom left and right key are not working
Dec17 left and right buttons works but drag problem
Dec18 right button non working and also no drag
Dec20 buttons working , drag sometimes works but most of the time not.

What i noticed is that using the kext in your repository is that drag is working but the mouse pointer speed is faster even if i config it to be really slow.

**Comment by stevezhengshiqi** [comment]
@tmbt78 Thank you for testing! It seems like some codes in Dec 17 cause the drag problem. 

I believe the touchpad kext in v1.2.9 is half v2.0.1 native branch and half v2.1.4 master branch. I prefer higher pointer speed at that time and v2.1.4 is so slow, so I transplanted many codes from VoodooI2C v2.0.1 native branch. 
In the later release after v1.2.9, I just directly use VoodooI2C official version.

**Comment by loweets** [comment]
试了下，你下面发这个驱动完全不行，左键按下后光标根本拖不动

**Comment by tmbt78** [comment]
@stevezhengshiqi Hi and sorry for the delay but i got really busy at work ... I tried your version but it doens't work. The trackpad gesture are very responsive but i can't left click or right click using the bottom corners of my trackpad. It only works the single tap as left click but no drag and drop.
That's a pity because the gestures are really responsive ...

Mattia

**Comment by stevezhengshiqi** [comment]
@tmbt78 @loweets The kext I gave is the elder version of VoodooI2C by using `git reset --hard <commit_id>` and build by xcode. I may stop testing since it's not efficient(I have to send here and wait for feedback) and I personally couldn't feel the drag problem. Sending problem description to https://github.com/alexandred/VoodooI2C/issues is highly recommended.
