### ISSUE TITLE
Sleep/Power Problems 

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro#179]
Hello
I have some problems after fresh install.
sometimes after I'm not using the notebook and it goes into sleep mode , when I try to wake hime up I see only quarter of the screen and sometimes I see the screen is backlight and some screen glitches.

is there an option to fix this issues ?

**Comment by stevezhengshiqi** [comment]
@macguru341 Hi, the quarter screen is related to your HiDPI setting. Please disable it or using the one-key-hidpi provided in this github and choose 1424x802 resolution.

**Comment by netyjq** [comment]
你好，我也遇到了类似问题，我的是小米笔记本pro 15.6 i5 8G版本，我刷了 one-key-hidpi 脚本，但还是会遇到以下几种情况：
1. 睡眠后无法唤唤醒，或者等上一分钟后系统才出现登录页面，登录页面出现之前电源灯和键盘大小写灯正常
2. 睡眠后直接卡死不能输入账号密码不能操作鼠标触控板，只能强制关机重启
3. 睡眠后唤醒画面缩放了，只能强制关机重启

**Comment by stevezhengshiqi** [comment]
@netyjq 你好，请卸载one-key-hidpi脚本并使用本仓库里的。

**Comment by netyjq** [comment]
@stevezhengshiqi 谢谢 非常棒啊  真的生效了

**Comment by stevezhengshiqi** [comment]
Will close this issue because it's an old topic and already been solved.
