### ISSUE TITLE
键盘鼠标无法输入

### ISSUE THREAD

**Issue by ayaup** [daliansky/XiaoMi-Pro#18]
我是小米13.3 带指纹本本，之前成功安装过驱动，无奈声卡唤醒后无法工作，想调整下，无奈没有备份uef，导致无法正常启动，使用最新版本后，全程很流畅的跑起来，当输入密码登陆的时候，无法正常输入，尝试添加键盘鼠标驱动依然无果。望能尽快修复下。

**Comment by daliansky** [comment]
小米有很多种笔记本的型号，我维护的是小米PRO的型号，EFI你可以借鉴，它并不通用
