### ISSUE TITLE
Installation runs in a loop on the samsung evo

### ISSUE THREAD

**Issue by efreyu** [daliansky/XiaoMi-Pro#183]
Hello. First of all I want to say thanks to the creators of this project.
I have a problem, I hope for your help.
I can't install High Sierra or Mojave. The system reboots in the second step with a black screen and the words "15 minutes left". 
If at this step I switch to the old installation mode by pressing ⇧⌃⌥⌘W and then ⌘L then there will always be the error "Can not connect to /var/run/systemkeychaincheck.socket: No such file or directory" in the log.
I think that there may be a problem in the BIOS version, but I did not find information about it anywhere.
I hope for your help.

- Notebook: Xiaomi Mi Notebook Pro 15.6 i7/16Gb MX version
- Bios version: XMAKB5R0P0A07
- I replaced ssd on SAMSUNG 970 EVO MZ-V7E500BW 500Гб, M.2 2280, PCI-E x4, NVMe

[error.log](https://github.com/daliansky/XiaoMi-Pro/files/3153370/error.log)

**Comment by Menchen** [comment]
A quick search seem you just need to wait more .... source https://discussions.apple.com/thread/5474543

**Comment by efreyu** [comment]
Unfortunately, the system itself reboots and enters the reboot loop, I do not reboot it.

**Comment by efreyu** [comment]
The problem solved when i replaced ssd on another samsung ssd. Samsung 970 evo is not supported by clover.

**Comment by Menchen** [comment]
That's weir, I'm using 970 Evo right now...
