### ISSUE TITLE
touchpad not working after new efi folder

### ISSUE THREAD

**Issue by artemis77799** [daliansky/XiaoMi-Pro#187]
hi, today I replaced my efi partition files (october 2018) with the new ones in this github since I saw they have been updated, but after the restart i noticed that the touchpad is no longer working, i tried rebuilding the kext cache and rebooting but it still isn't working

**Comment by stevezhengshiqi** [comment]
Hi, please do the steps written in the `Tips for TrackPad` in the release.

1. Delete `BOOT` folder and `CLOVER` folder in your EFI partition and copy these two folders from this pack.

2. Run `Kext Utility.app`, or type `sudo kextcache -i /` in `Terminal.app`. Then restart.

3. If the trackpad still doesn’t work, try to press F9.

4. The final solution is to boot in Windows and play with the trackpad for a while, then restart into macOS.

* Make sure S/L/E and L/E are untouched!

**Comment by artemis77799** [comment]
Thanks, I tried that, but now my clover doesn’t even work anymore and the pc boots straight into windows.
If I paste the entire new EFI folder the pc boots but without touchpad working, if I paste only clover and boot folders it doesn’t start at all,
currently downgrading to my old efi folder ;(

**Comment by stevezhengshiqi** [comment]
Don’t forget to add boot item for your CLOVER if your pc boots straight into windows. And always delete the two folders and then paste the two folders from the latest release for clean proporse.

**Comment by artemis77799** [comment]
clover is the first boot option, it just gives me an error that i can't even read since it's too fast and goes to windows

**Comment by stevezhengshiqi** [comment]
You can add boot-argument -v to enable log display. An error log is needed for further discussion. Please read https://github.com/daliansky/XiaoMi-Pro/wiki/Problem-Report

**Comment by stevezhengshiqi** [comment]
I re-read your first post, and it seems like you are not using the EFI folder in release page.
v1.3.3 release is highly recommended, and don't forget to delete OC folder to keep your EFI folder clean.

**Comment by artemis77799** [comment]
I did what you said and everything worked! thank you so much, i noticed the trackpad is much better now than before (i still had the october release)
