### ISSUE TITLE
touchpad and sound not working after new efi folder

### ISSUE THREAD

**Issue by recre4te** [daliansky/XiaoMi-Pro#188]
https://github.com/daliansky/XiaoMi-Pro/issues/187
I did everything that was said here, but the touchpad did not work, and the sound also does not work and the windows stopped loading

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro/wiki/Problem-Report

**Comment by stevezhengshiqi** [comment]
Also make sure you are using Clover instead of OC. Release v1.3.3 is tested by hundreds of people and it’s stable.

**Comment by stevezhengshiqi** [comment]
https://github.com/daliansky/XiaoMi-Pro/releases

**Comment by stevezhengshiqi** [comment]
Closing the issue because of mistakenly using OC instead of Clover.
