### ISSUE TITLE
HDMI volume can not change

### ISSUE THREAD

**Issue by Andrew-Hello** [daliansky/XiaoMi-Pro#189]
Hi, I found the sound of HDMI monitor can not be changed In control panel. The output volume is gray and cannot be dragged. The monitor sound keep maximum always. Is there any method to adjust the output volume of HDMI? Thanks a lot.

**Comment by stevezhengshiqi** [comment]
Hi, macOS doesn’t natively support HDMI volume change. 

This is a google result that tell people how to use third party app to control volume.

I personally recommend to use monitor setting to change the brightness.

**Comment by stevezhengshiqi** [comment]
Since it’s an Apple problem, can not be solved in hackintosh. Closing the issue.
