### ISSUE TITLE
bluetooth not working on 1.3.3

### ISSUE THREAD

**Issue by artemis77799** [daliansky/XiaoMi-Pro#190]
![Screenshot 2019-05-15 at 20 03 10](https://user-images.githubusercontent.com/46961774/57798199-7c693400-774c-11e9-9644-7cd6c7ccce66.png)
My usb bluetooth dongle is no longer working on 1.3.3, bluetooth shows up as abilitated even if i have my usb dongle unplugged and there's no option to disable it

**Comment by Menchen** [comment]
https://github.com/daliansky/XiaoMi-Pro/wiki/Work-Around-with-Bluetooth
