### ISSUE TITLE
VoodooPS2Controller version

### ISSUE THREAD

**Issue by sakoula** [daliansky/XiaoMi-Pro#191]
Hi I noticed that you are using a new VoodooPS2Controller version. However I cannot find it anywhere else on the web. Is this something that you have build it specifically for the Xiaomi Pro.

I have a XiaoMi-Air-6200U

Thanks!

**Comment by stevezhengshiqi** [comment]
Hi, you can find source code of most kexts in the Credits section of [[README.md]]. New version of VoodooPS2’s source code is at https://github.com/acidanthera/VoodooPS2

**Comment by sakoula** [comment]
thanks @stevezhengshiqi for the super fast reply!!!!!!!
