### ISSUE TITLE
The computer won't shut down

### ISSUE THREAD

**Issue by Raphencoder** [daliansky/XiaoMi-Pro#195]
I think my problem is due to a bad installation, but if someone had the same problem and fixed it I'll be happy to know how. 

I just update to Mojave everything work just great, the trackpad is so much better ! But everytime I shut down the 'mac', the computer restart..
Plus when I choose mac option it tells the following: 
![restart](https://user-images.githubusercontent.com/33024433/58239673-c4d6b200-7d49-11e9-98b2-da9c4aee78d1.jpg)

Also the clover start choosing boot is not working and it do not propose me the usual boot but instead of an Opencore Boot menu like this:
![OpenCore](https://user-images.githubusercontent.com/33024433/58239504-775a4500-7d49-11e9-9e6e-6b8aafe95365.jpeg)

Anyone had the same issue or solution for this issue ?
Thanks !

**Comment by stevezhengshiqi** [comment]
Hi, you are using OpenCore bootloader, and it's a known issue that device won't shutdown with OpenCore+VoodooI2C. See https://github.com/daliansky/XiaoMi-Pro/issues/192.

You should delete /EFI/OC folder so the device will only use CLOVER.

**Comment by kevkol** [comment]
I have the same issue. I deleted the /EFI/OC folder, my system will now start with windows every time. How to get clover back?

**Comment by stevezhengshiqi** [comment]
Hi @keckol, for daily use, EFI folder from release page: https://github.com/daliansky/XiaoMi-Pro/releases is always a reliable choice.

**Comment by Raphencoder** [comment]
I'll try to replace it but I have the same problem than @kevkol and I'm stuck to windows for now

**Comment by kevkol** [comment]
@Raphencoder 
I was able to get back to clover with the following steps: 
I did a full format of my EFI folder, after I mounted it with windows. There had been some undeletable corrupted data in there for me.  
I copied an earlier backup of the EFI Folder to my EFI partition.
I copied the updated version of the release page (link by @stevezhengshiqi ) to my EFI partition and replaced duplicates. 
Now you need to consider that the BIOS will change to boot device order, if you boot one time with an EFI which is not configurated properly. That means double check the boot order in your bios menu.
=> now everything is working again with clover

**Comment by Raphencoder** [comment]
Thanks ! That works for me too
