### ISSUE TITLE
Unable to connect to 4K display

### ISSUE THREAD

**Issue by netyjq** [daliansky/XiaoMi-Pro#198]
当我连接上4K显示器的时候，我的笔记本和显示器都黑屏了，并且我的笔记本电脑无法亮屏，不论是盒盖过几秒开启，还是插拔HDMI线，都无法亮屏，只能强制关机。有没有什么好办法解决此问题，顺便说下，连接2K显示器没问题

**Comment by stevezhengshiqi** [comment]
不要创建重复问题哦，请注意查看https://github.com/daliansky/XiaoMi-Pro/issues/117

**Comment by netyjq** [comment]
好的 我去试试 。

**Comment by netyjq** [comment]
@stevezhengshiqi  大神你好，我按照 https://github.com/daliansky/XiaoMi-Pro/edit/master/BIOS/DVMT_and_0xE2_fix/README_CN.md 这个教程做了，但是第7，8步骤我搜索了内容无法找到相关的代码，接下来该怎么做呢？


7. 删除帧缓存补丁

- 打开 `/EFI/CLOVER/config.plist`，删除以下代码：
```
<key>framebuffer-fbmem</key>
<data>AACQAA==</data>
<key>framebuffer-stolenmem</key>
<data>AAAwAQ==</data>
```

8. 开启 `RtcHibernateAware`

- 打开 `/EFI/CLOVER/config.plist`，找到以下代码：
```
<key>NeverHibernate</key>
```

- 替换为：
```
<key>RtcHibernateAware</key>
```

**Comment by netyjq** [comment]
最新进展，第7步我已经成功删除了，第8步无法找到代码。我试着启动mac os，接上4K显示器依然是黑屏的，合上盖子再打开也是如此，插拔也无法恢复正常。

之前是因为我用默认的记事本软件打开无法搜索到，换成notepad++可以搜索到，但是第8步里的代码依然无法搜索到。

**Comment by netyjq** [comment]
最新进展：刷BIOS和帧缓存均无效，无意间用USBC转接HDMI 4K显示器可以正常显示，虽然只有30HZ，但是凑合用着。
