### ISSUE TITLE
短暂休眠后按开机键五国

### ISSUE THREAD

**Issue by yipingw** [daliansky/XiaoMi-Pro#199]
系统版本：10.14.5
EFI版本：1.3.3
机型：i5 8G 256G
标准安装，无任何杂项
现象：在无电源的情况下电脑短时间休眠，按开机键试图唤醒电脑，结果直接显示五国。

**Comment by stevezhengshiqi** [comment]
反馈问题请贴出系统启动后生成的崩溃日志。

**Comment by yipingw** [comment]
待提供进一步log再开issue.
