### ISSUE TITLE
几个小问题？

### ISSUE THREAD

**Issue by wuchuguang** [daliansky/XiaoMi-Pro#2]
1, 为什么触摸板的需要睡眠再唤醒才能用？
2, 勾上：有shu标或无线触控板时忽略内建触控板 无效（插上USBshu标，还可以用触控板！）

**Comment by stinby** [comment]
1，有时桌面右上角栏的电量图标百分比数值卡死，一直不会变。但是锁屏登录界面的电量数值是正确的。睡眠再唤醒，桌面右上角栏的电量图标百分比数值才会刷新一次。
2，有时偶尔声卡无声，重启后恢复正常。
3，屏幕亮度调节后，不能保存亮度，重启后屏幕亮度又恢复出厂值了。
4，本子自带的蓝牙无法正常使用，mac地址全00。 如果在windows系统下重启后再进入MacOS，蓝牙可以搜索到手机等其他蓝牙设备，但是也连接失败。

**Comment by daliansky** [comment]
@ 目前的触摸板的驱动还不完善

**Comment by daliansky** [comment]
@wuchuguang 目前触摸板的驱动还不完善

**Comment by daliansky** [comment]
@stinby 1.电量更新可以通过修改ssdt进行修正;2.声卡驱动偶尔会存在开机无法加载的情况,在没有更新EFI的情况下可以使用lilu debug版本加载AppleALC;3.亮度保存需要增加驱动EmuVariableUefi-64.efi;4.Intel的蓝牙截止到目前还无解;

**Comment by kvn1351** [comment]
@daliansky Hey man, could you please add support for Brightness control?

**Comment by daliansky** [comment]
@kvn1351 After the update, I will improve it
