### ISSUE TITLE
ALCPlugFix: script error when /usr/local/bin not exists 

### ISSUE THREAD

**Issue by 5night** [daliansky/XiaoMi-Pro#202]
fix:
create the folder if not exists 

log:
支持小米笔记本电脑Pro(ALC298, 节点99)
===============================================
(1) 开启 ALCPlugFix
(2) 关闭 ALCPlugFix
(3) 退出
你想选择哪个选项? (1/2/3):1

正在下载声卡修复文件...
下载完成

正在卸载...
Password:
卸载完成

正在拷贝声卡修复文件...
cp: directory /usr/local/bin does not exist
cp: directory /usr/local/bin does not exist
拷贝完成

正在修复权限...
chmod: /usr/local/bin/ALCPlugFix: No such file or directory
chown: /usr/local/bin/ALCPlugFix: No such file or directory
chmod: /usr/local/bin/hda-verb: No such file or directory
chown: /usr/local/bin/hda-verb: No such file or directory
修复完成

**Comment by Menchen** [comment]
Running `mkdir -p -m 775 /usr/local/bin && chown $USER:admin /usr/local/bin` shuold fix it.
