### ISSUE TITLE
HiDPI有可以正常睡眠的更高分辨率吗？

### ISSUE THREAD

**Issue by 0x112** [daliansky/XiaoMi-Pro#205]
请问有接近1600x900的能正常睡眠的分辨率吗？
相关问题：https://github.com/xzhih/one-key-hidpi/issues/52

**Comment by stevezhengshiqi** [comment]
小米PRO 10.14睡眠唤醒后不花屏的分辨率最大就是1424x802，是小米黑苹果群的群友共同试出来的。

你也可以开启1920x1080的hidpi，也就是3840x2160，借助RDM，不会花屏。

**Comment by 0x112** [comment]
好的，一定要在RDM里面设置才不会花屏吗？

**Comment by stevezhengshiqi** [comment]
@0x112 在RDM里设置也会花屏，分辨率必须低于1424hidpi 或者开 1920hidpi才不会花屏

**Comment by 0x112** [comment]
但是我屏幕是1920x1080的，开1920的hidpi，不是等于没开一样吗？或者说是不是比如我2k分辨率的屏幕，开1920x1080的hidpi就不会花屏？

**Comment by stevezhengshiqi** [comment]
1920的hidpi分辨率是3840x2160呀，怎么会跟没开一样。。

**Comment by 0x112** [comment]
也就是说要在HiDPI脚本手动输入 3840x2160 吗？

**Comment by stevezhengshiqi** [comment]
嗯嗯，syscl的那个脚本应该可以，我一般转成base64自己填进显示器配置文件。

**Comment by 0x112** [comment]
好的，改天试试，谢谢

**Comment by cwr31** [comment]
1600*900 不知道可以不

**Comment by stevezhengshiqi** [comment]
@cwr31 不行的 最大就是1424x802。
