### ISSUE TITLE
Audio problems with new release

### ISSUE THREAD

**Issue by artemis77799** [daliansky/XiaoMi-Pro#207]
Hi, I'm a music producer so audio is important to me, recently I updated my efi folder with the latest release in this github and I noticed that audio is messy and buggy when I produce on every audio program I use so I think it's a coreaudio related problem. I tried downgrading to my old efi foulder and the problem disappeared so I'm sure that the new efi folder is the cause. Since I want my efi folder to be updated but I also want my music programs to work as they should, wich kexts should I replace in my efi folder with the old ones? which are audio related kexts? I'm pretty new to hackintosh and I can't figure it out myself, thanks

**Comment by Menchen** [comment]
If you can tell us what version did you downgrade to it will be helpful... Also, can you describe what exactly `audio is messy and buggy` is?

**Comment by artemis77799** [comment]
> If you can tell us what version did you downgrade to it will be helpful... Also, can you describe what exactly `audio is messy and buggy` is?

I used to have the 1.2.9 release I think since I hackintoshed this laptop at hte end of january 

The main problem is that some audio clips randomly stop playing while the others are playing and they come back after something like 2/3 seconds and this happens very ofter (1 time every 10 seconds of a track), this happens with every program that uses coreaudio: i tried logic, ableton and fl studio, all three with the same problem

**Comment by Menchen** [comment]
@artemis77799 Weir that I can't reproduce this problem using Ableton(Added two random midi instruments with one random midi track each, and play at the same time)... Maybe because I'm not using the latest release(AppleALC v1.3.7)... By latest did you mean the EFI from github repo directly or via release page?

**Comment by artemis77799** [comment]
> @artemis77799 Weir that I can't reproduce this problem using Ableton(Added two random midi instruments with one random midi track each, and play at the same time)... Maybe because I'm not using the latest release(AppleALC v1.3.7)... By latest did you mean the EFI from github repo directly or via release page?

the last one in the release page

**Comment by artemis77799** [comment]
nvm, I replaced AppleALC with the old version that was in my old working efi folder but the problem is still there so it's not AppleALC related..

**Comment by artemis77799** [comment]
ok I think i might be crazy but, I tried every release on this github and the problem is still there, the only efi folder that eliminates the problem is my old one, and I don't know which release is that at this point. Here it is 
[backup efi.zip](https://github.com/daliansky/XiaoMi-Pro/files/3266699/backup.efi.zip)

**Comment by artemis77799** [comment]
It was a config.plist problem, solved!
