### ISSUE TITLE
AppleBacklightInjector breaks brightness control

### ISSUE THREAD

**Issue by PavelLJ** [daliansky/XiaoMi-Pro#21]
Hello! Got macOS installed with that nice clover folder, thanks for hard work! I didn't got brightness control at all before I deleted AppleBacklightInjector, so I think it's a problem.
Also, as I don't want to open new issue for just a question: why not SSDT USB injection but patched InjectAll?

**Comment by stevezhengshiqi** [comment]
In fact, we patch both SSDT(SSDT-MiPro_USB.aml) and InjectAll. Maybe it's for double insurance I think. Thanks for your reporting and I will test if the combinations of SSDT and non-patched version of USBInjectAll is sufficient enough.

**Comment by stevezhengshiqi** [comment]
For the brightness control, what I did is what Rehabman's guide said:https://www.tonymacx86.com/threads/guide-laptop-backlight-control-using-applebacklightinjector-kext.218222/. Maybe you can provide trouble shooting files in that thread. If you are OK with your situation, it's fine. I guess perhaps you have installed IntelBacklight.kext or ACPIBacklight.kext or some other backlight kexts before?

**Comment by PavelLJ** [comment]
> In fact, we patch both SSDT(SSDT-MiPro_USB.aml) and InjectAll. Maybe it's for double insurance
If SSDT is working, it will overwrite InjectAll data (except you will throw -uia_ignore_rmcf as boot flag), so at first try unpatched InjectAll.

> I guess perhaps you have installed IntelBacklight.kext or ACPIBacklight.kext or some other backlight kexts before?
Nope, I was really upset when saw that brightness is not working and immediately went to EFI/CLOVER/kexts/others and ACPI/patched. I saw PNLF and also Config, which should make AppleBacklight working, so I just deleted the injector. Now it's working, regulated by 1/5 of one division (I think it's a feature of keyboard driver to make that accurate control, on Mac it's working via CMD+Shift)

**Comment by PavelLJ** [comment]
Some more questions: why you need to enable TRIM on high Sierra with APFS? Isn't it working by default? What about kext patches at all? I mean, what exactly does that numerous cdmi-audio, extended icon patch, 1536MB->2048 (is it just for looking or it does something?)

**Comment by stevezhengshiqi** [comment]
Thanks for feedback. I totally agree with you about disabling TRIM patch. Personally I disable this patch, and I also found TRIM supported in System information. I will try to persuade daliansky to do that.
1536MB->2048 patch is for HDMI Display. Sometimes the HDMI Screen will not work well if VRAM is 1536mb.
HDMI-audio path is for HDMI audio for sure. The audio channel has to be adjusted to let HDMI speakers work.
Extended icon patch is used when some external disks plug into the laptop, the icon of that disk appears with a yellow disk or something like that, which is not normal.
Sorry for "Intel GPU FW disabling", could you explain more about that? I am also trying to make patches clean and also ensuring them work well.

**Comment by PavelLJ** [comment]
> I have the same question for "Intel GPU FW disabling"

I guess It was temporary fix for Intel HD620, because, quote from [IntelGraphicsFixup
](https://github.com/lvs1974/IntelGraphicsFixup)
> Allows booting without -disablegfxfirmware boot argument with Kaby Lake Graphics in 10.13

Okay, done with that - it's unnecessary. On other side, there is also "igfxfw=1" which means IntelGraphicsFixup loads GuC microcode itself (didn't know why dialinsky did that but okay, maybe it have a reason). Okay, second flag "igfxrst=1" is related to that awful Apple-on-boot logo glitch which is kinda fixed with this argument (from [IntelGraphicsFixup README.md](https://github.com/lvs1974/IntelGraphicsFixup/blob/master/README.md) ).
Anyway there is third argument - "shikigva=1" which is REEAAALY rare needed and used, as last Shiki determines best configuration itself. Looks like "abm_firstpolldelay=10000" has too big value too, maybe it was chosen random but I don't care, at least it works as expected. Ah, stop, maybe it doesn't - is it healthy that 2-3 times a second there is such thing in log? I mean, it's too often.
`coreduetd    CDDBatteryMonitor:    received batterycallback, currentPercentage:90.010447!
powerd    Battery time remaining posted(0x200000000480140) Time:320 Source:Batt`

**Comment by stevezhengshiqi** [comment]
I found that if I uncheck -disablegfixfirmware, the display screen can't show up after sleep. It's strange since keyboards, USB ports are working well except the display. If I check it again, the problem is gone.

shikigva=1 is there because according to Shiki's documents,

> How can I enable Intel online video decoder when AppleGVA enforces offline?
Add shikigva=1 argument to boot-args.[https://github.com/vit9696/Shiki/blob/master/Manual/FAQ.en.md](url)
the Intel graphics can decode videos better I think. Also, iTunes issue is not related to this argument since it's only about graphics. I have tried to move 'shikigva=1' before, and the QucikTime Player doesn't behave well when I play a full-screen mp4.

**Comment by PavelLJ** [comment]
> I found that if I uncheck -disablegfixfirmware, the display screen can't show up after sleep.

Found that too, that's a play between IntelGraphicsFixup FW injector and macOS stock functionality.

> the Intel graphics can decode videos better I think. Also, iTunes issue is not related to this argument since it's only about graphics. I have tried to move 'shikigva=1'

Well it's not, because it affects on Intel QuickSync which is media protocol that cause iTunes on High Sierra crash [example here](https://github.com/vit9696/Lilu/issues/20) as you can see, sometimes shikivga=1 does opposite things & HW acceleration wouldn't work. Shiki determines best config automatically, I'll check full screen video playback as soon as possible, but without that flag iTunes works flawlessly.

**Comment by stevezhengshiqi** [comment]
Thanks for all your effort, I will put your name in the credit if you don't mind. The iTunes and full-screen QuickTime Video don't have problem after shikigva=1 is moved on my device. 
In summary, I will submit these changes to daliansky:
  Delete the Trim patch in config
  Delete "shikigva=1"
  Replace USBInjectAll_patched with an original kext
  Translate comments of some patches in KextsToPatch for better understanding
Also, compare with config samples in https://github.com/RehabMan/OS-X-Clover-Laptop-Config, I decide to change "XMPDetection=No" to Yes. Maybe it can boost the memory bank speed.

**Comment by stevezhengshiqi** [comment]
Back to the title, I still think AppleBacklightInjector is needed. If I remover it, the lightnesss range would be very small. I heard that you have a fresh install recently, maybe it’s a chance to try SSDT-PNLF+ config patch + AppleBacklightInjector.kext.

**Comment by PavelLJ** [comment]
I got brightness working with SSDT-PNLF only, as I hate Windows too much I wiped all SSD before it even booted for first time :rofl , so I don't know how wide should be brightness range

**Comment by PavelLJ** [comment]
Also the thing I noticed - I never needed DVMTFixup, so maybe it's not needed too?

**Comment by stevezhengshiqi** [comment]
I need it because I don't inject any graphics id into config, in order to let IntelGraphicsFixup to choose appropriate graphics id for me. And IntelGraphicsFixup returns 0x59160000, which is different from your id(0x591b0000). Your config has minstolen patch which don't suit for 0x59160000, and IntelDVMFixup can automatically fix that for me.

**Comment by stevezhengshiqi** [comment]
I think the reason why daliansky just uses Rehanbman's HD620 config is that HD620 and UHD620 are two generations. 0x59160000 suits for our laptop better.

**Comment by PavelLJ** [comment]
> 0x59160000 suits for our laptop better.

Well it's quite subjective, but being honest I didn't noticed any difference, maybe we need to benchmark that.

> I don't inject any graphics id into config, in order to let IntelGraphicsFixup choose an appropriate graphics id for me. 

As far as I know RehabMan doing same (injecting wrong, 8086 id for IntelGraphicsFixup to override that). I tried your setup with AppleBacklightInjector and yeah - range is wider and it works, while on dialinsky's folder it doesn't work for me.

**Comment by stevezhengshiqi** [comment]
I can explain why 0x59160000 suits for our laptop better. If you look at SSDT-IGPU from Rehabman's GitHub(https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-IGPU.dsl), you can see `// Kaby Lake-R/UHD620
            0x5917, 0, Package()
            {
                "AAPL,ig-platform-id", Buffer() { 0x00, 0x00, 0x16, 0x59 },
                "model", Buffer() { "Intel UHD Graphics 620" },
                "hda-gfx", Buffer() { "onboard-1" },
                "device-id", Buffer() { 0x16, 0x59, 0x00, 0x00 },
            },`

**Comment by stevezhengshiqi** [comment]
I don’t find one, and perhaps I didn’t try very hard since I am satisfied at current situation. It’s my own fault because I am lazy.

**Comment by stevezhengshiqi** [comment]
Hi, I want to inform you that the CLOVER folder is clean now. Thanks for your help.
