### ISSUE TITLE
Disabling the Internal Bluetooth 

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro#24]
Hello
Thanks for all the support for this machine.
Just wondering, if the internal Bluetooth isn’t working why don’t you update the clover folder with some patch that will disable it and will give us the option to use external dongle ?
I’m sure you can do it fast as I see you are the master of this hack. I tried do it by myself and share it but I was working on it for the last 2 weeks without success .

Hope you can help us
Thanks

**Comment by stevezhengshiqi** [comment]
Hi, I can help you with disabling internal Bluetooth. The reason why our clover folder leave it open is that it can be activated in someway. For example, you can first start Windows and then restart in MacOS to activate MacOS. In addition, we think that we should leave the choice to public and let them decide to disable the bluetooth or not, instead of us.

Since you have worked on it for last 2 weeks so I believe you have read this thread [https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/](url). 
- First, delete EFI/CLOVER/kexts/Other/USBInjectAll_patched.kext(or USBInjectAll.kext) and replace it with USBInjectAll.kext(which is in the archive below)
- Second, delete EFI/CLOVER/ACPI/SSDT-MiProUSB.aml(or SSDT-UIAC.aml) and replace it with SSDT-UIAC.aml(which is in the archive below)
- Restart, and wait for your good news!
[Archive.zip](https://github.com/daliansky/XiaoMi-Pro/files/1995988/Archive.zip)

**Comment by macguru341** [comment]
God....thanks a lot for your help , I will try it later in the night

**Comment by macguru341** [comment]
thanks - that works great

**Comment by orditeck** [comment]
Exactly what I was looking for, thanks @stevezhengshiqi!

**Comment by stevezhengshiqi** [comment]
@orditeck Thank you for advice. I will add it.

**Comment by Neolo** [comment]
I've noticed that it breaks 1st USB 3 port from the top. I kept .aml file but reverted your USBInjectAll.kext back to what I had before. Now internal BT still off, and USB port started working.

**Comment by stevezhengshiqi** [comment]
@Neolo USBInjectAll should be the original one from Rehabman's github. Using a hotpatch(SSDT-USB.aml) to modify the port information. Everything should work fine because I carefully follow the guide https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/.

**Comment by stevezhengshiqi** [comment]
@Neolo I am in a summer school now, and I don't bring a USB 3.0 drive. I will have chance to test a month later.

**Comment by alexmenn** [comment]
@stevezhengshiqi Hi!! How can we now disable bluetooth with actual EFI? USBPorts.kext doesnt exist to replace it, now we have USBPower.kext.
Should we delete USBPower.kext and install USBPorts.kext in clover/kexts/other ?

**Comment by stevezhengshiqi** [comment]
@alexmenn Yes. If you soldered your BT, you will need another USBPorts.kext in https://github.com/stevezhengshiqi/XiaoMi-Pro/issues/7 .

**Comment by isuke01** [comment]
Just curious, Can I use BCM94360CS2 Macbook Air 13, + adapter for m2 ? And complicate it more, use it over USB adapter to m2? or I just have to use m.2 slot or even this will not work ?
Card: https://www.aliexpress.com/item/Original-A1465-A1466-Wifi-Airport-Bluetooth-Card-For-Macbook-Air-11-13-Laptop-2013-Years/32637520988.html

**Comment by Giannidmg** [comment]
with the latest kext update, how do I disable Bluetooth (for use dongle) without losing the two USBc ports?

**Comment by stevezhengshiqi** [comment]
@Giannidmg First, delete `SSDT-USB` in `/ACPI/patched` and `USBPower` or `USBPorts` in `/kexts/Other`. 
Then copy the `USBPorts` at the 2nd floor of this page into `/kexts/Other`, and restart.

**Comment by Giannidmg** [comment]
ok now it works thanks

**Comment by Chazy12** [comment]
@stevezhengshiqi i tried all what you wrote, but mine don't work. So I think I didn't understand something..
I've a Bluetooth USB dongle, installed kext from rehab, changed the ssd-usb from EFI with yours but my system finds the internal Bluetooth and not the dongle..

**Comment by Menchen** [comment]
@Chazy12 read readme about how to disable internal bt

**Comment by Chazy12** [comment]
@Menchen where?

**Comment by Menchen** [comment]
https://github.com/daliansky/XiaoMi-Pro

**Comment by Chazy12** [comment]
@Menchen already read that. But if I disable internal Bluetooth, my USB dongle Bluetooth not working too..

**Comment by Chazy12** [comment]
> Hi, I can help you with disabling internal Bluetooth. The reason why our clover folder leaves it open is that it can be activated in someway. For example, you can first start Windows and then restart in MacOS to activate bluetooth. In addition, we think that we should leave the choice to public and let them decide to disable the bluetooth or not, instead of us.
> 
> Since you have worked on it for last 2 weeks so I believe you have read this thread [https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/](url).
> 
> * Delete `EFI/CLOVER/ACPI/SSDT-USB.aml` and replace it with the `SSDT-USB.aml` below.
> * Restart, and wait for your good news!
> 
> If you want to use an external BT dongle, please read Rehabman's repository: https://github.com/RehabMan/OS-X-BrcmPatchRAM
> 
> [SSDT-USB.aml.zip](https://github.com/daliansky/XiaoMi-Pro/files/2281169/SSDT-USB.aml.zip)
> 
> UPDATE: The archive is updated on 13th August, 2018.
> 
> EDIT: The newest EFI release uses a new USB Injection method, please replace the following archive with the one in `/EFI/CLOVER/kexts/Other/` to disable BT.
> [USBPorts.kext.zip](https://github.com/daliansky/XiaoMi-Pro/files/2707566/USBPorts.kext.zip)

@Menchen this one.

**Comment by Chazy12** [comment]
And my ssdt-usb in EFI is ssdt-usbx. So I renamed it into that folder, but nothing.

**Comment by Menchen** [comment]
So after replacing usbport kext external bt still dont work? Which kext did you use from rehab? Also you only need to replace usbport and not ssdt-usb.aml ..

**Comment by stevezhengshiqi** [comment]
@Chazy12 Hi, SSDT-USBX is totally different from SSDT-USB. Just add USBPorts.kext given in the 2nd floor and restart.

**Comment by Chazy12** [comment]
> @Chazy12 Hi, SSDT-USBX is totally different from SSDT-USB. Just add USBPorts.kext given in the 2nd floor and restart.

I replaced the ssdt-usbx with the original one, updated only the kext then rebooted. On the restart I only see the Bluetooth is not active, so my USB dongle don't work..

**Comment by Chazy12** [comment]
@Menchen I used brcmfirmwarerepo and brcmpatchram2 couse I see my device is in the list of the patchram..

**Comment by Menchen** [comment]
Maybe it's your usb dongle fault.... because usb dongle shouldn't use reh's kext as you said(bmcram something like that is for internal non native wifi card bt to work with hack)

**Comment by Chazy12** [comment]
@Menchen the strange thing is that yesterday was working after replacing the ssdt-usbx and the kext. This morning was not working anymore. I used this dongle on my hackintosh desktop and works there.. I think is something related to the disabling of internal Bluetooth..

**Comment by Chazy12** [comment]
@stevezhengshiqi @Menchen so, an update: if I put the dongle in USBC adaptator, the dongle works. If I put it in the internet USB, the dongle don't work.. uhm..

**Comment by Menchen** [comment]
By internal you mean left side usb a port?

**Comment by Chazy12** [comment]
@Menchen yes. The both of them

**Comment by Chazy12** [comment]
Update again: after some minutes, on the USBC adaptor, don't work anymore.. grrr

**Comment by Chazy12** [comment]
> @Chazy12 Hi, SSDT-USBX is totally different from SSDT-USB. Just add USBPorts.kext given in the 2nd floor and restart.

do you've a solution?

**Comment by Chazy12** [comment]
@stevezhengshiqi do you've a solution?

**Comment by Chazy12** [comment]
@stevezhengshiqi another problem i've is the HDMI out.. Not working the output and i have to restart my laptop to let the display work again..

**Comment by stevezhengshiqi** [comment]
@Chazy12 Never heard about the problem like you before. You can try to replug the adapter or use another adapter.

For the HDMI, try to remove `-cdfon` and restart. Don't forget to close the lid after connecting the external monitor for a few seconds.

**Comment by Chazy12** [comment]
Where I've to remove the -cdfon?!
Thanks again.

**Comment by stevezhengshiqi** [comment]
config.plist

**Comment by acoutts** [comment]
Hi- there is now an Intel bluetooth kext that will upload the firmware on boot. This could work for you: https://github.com/zxystd/IntelBluetoothFirmware
