### ISSUE TITLE
非Bug，仅建议，可否提供原机的DSDT文件呢？

### ISSUE THREAD

**Issue by lgs3137** [daliansky/XiaoMi-Pro#28]
你好，看了下你的SSDT Hotpatch写得很好更新日志也很详细，可否也上传原机提取的DSDT文件方便后人快速适不同机型的Hotpatch呢？

**Comment by stevezhengshiqi** [comment]
谢谢你的赞美，我会转达给作者的。
这是原机DSDT
[DSDT.zip](https://github.com/daliansky/XiaoMi-Pro/files/2011369/DSDT.zip)

**Comment by lgs3137** [comment]
@stevezhengshiqi 👌感谢分享~

**Comment by lgs3137** [comment]
才发现 commits 里面也有记录。。。
