### ISSUE TITLE
activate the handoff and continuity feature?

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro#29]
Finally my Bluetooth is working fine and I have my Magic Mouse 2 works but I don’t have the handoff and continuity feature in the settings , why is that? I’m using a 4.0 Bluetooth dongle that was recommended for hackinrosh .

**Comment by stevezhengshiqi** [comment]
To opne Handoff and continuity feature, you need an internal wireless card + Bluetooth dongle. A USB Wireless card is not supported though you have a Bluetooth dongle.

**Comment by PavelLJ** [comment]
Well this may be fixed with custom low-profile M.2 Key M > Key A adapter with additional USB cable, but as far as I know they're not exist. More information on tonymacx86 or [hackintosh-forum-de](https://www.hackintosh-forum.de/index.php/Thread/36796-M-2-key-M-to-M-2-key-A-E-for-WIFI-BT-adapter/)

**Comment by influenist** [comment]
Hi,

Internal wifi is fixed for Xiaomi Pro and probably also Notebook Air 12.5 / 13.3. I'll update during one of these days the forum post on HF.de. Are you located in Poland @PavelLJ if so PM me for Skype or QQ.

@daliansky I'm building a similar ACHI hotpatch build work is 75% done. Might you be able to add it to your clover configurator to widen XioaMi support?

**Comment by PavelLJ** [comment]
@influenist I'm from Belarus, BTW less than 100km from Poland. Did you meant Broadcom Key M > A/E stuff or Intel wireless? Dialinsky is quite busy now, I think you should contact with @stevezhengshiqi for pull requests.

**Comment by stevezhengshiqi** [comment]
@influenist Please see my screenshot. I am a living example of people who have handoff open. This is my notebook structure, as I said, you need an internal wifi adapter to let handoff work.
![img_0488](https://user-images.githubusercontent.com/36894554/40394267-54b3841c-5e55-11e8-8103-02c22c411147.jpg)

**Comment by PavelLJ** [comment]
@stevezhengshiqi what kind of port is under WLAN_LTE? I'm pretty sure it's pinned and can be used for WiFi+BT, but I can't understand is it key B, or A, or E?

**Comment by influenist** [comment]
Hey @stevezhengshiqi this is the adapter from our friends Wxxtfu, correct? Did you solder the BT ports on the LTE slot pin 4 and 6 like below?

![e6b2a1bbf46b818129eeaedd88e889fb](https://user-images.githubusercontent.com/22964559/40490736-a306c56c-5f6c-11e8-82fd-7478882a3194.jpg)

I currently have M.2 key to key B with an A+B key, which looks like below. Hence I didn't test it with my current clover build for Mi NB Air 12.5. Only issue is form height size.

![img_20180524_155558_hht](https://user-images.githubusercontent.com/22964559/40491034-5a4f045a-5f6d-11e8-83fc-5326a100f92c.jpg)

I received the Mi NB Pro yesterday. Need to see if the Webcam header (pinout) is the same, to see if we can USB lanes an exclude soldering.

**Comment by stevezhengshiqi** [comment]
@influenist The one I said 

>  some people successfully soldered the bluetooth on that port.

is exactly the guy who solder the BT ports on the LTE slot pin 4 and 6 in your picture. What's more, the screenshot you give is shotted by him. We discussed a lot and I found that it's high-risky and skill-reuqired to solder the BT. So I give up and use USB BT.

**Comment by influenist** [comment]
@stevezhengshiqi true, hence I got in touch with them for the following less-risky option: 
Theoretically the webcam port offers the needed USB lanes. Hence a splitter cable for this port could work. Do you have a picture from the webcam port on NB Pro? Is it identical to the on below?

![img_20180524_165124](https://user-images.githubusercontent.com/22964559/40493595-54cbb7c0-5f73-11e8-9a93-a3db1e3c95ca.jpg)

![img_20180524_165156](https://user-images.githubusercontent.com/22964559/40493416-fc426c84-5f72-11e8-892d-2d4aeb26df34.jpg)

**Comment by influenist** [comment]
@PavelLJ you live in Lviv perhaps? Regarding your comment, if there is a soldered port there at the LTE location, it would be a KEY A. Till this moment I haven't seen any key B to A+E converter cards. The one @stevezhengshiqi is using is a Key M to Mini PCI-E if I am correct.

@stevezhengshiqi did you need to use a PCI hotpatch (acpi) to enable the card? Seen there is a SSDT-PCIList.aml?

**Comment by PavelLJ** [comment]
@influenist 
1) Belarus isn't Ukraine, btw I'm in Mins but sometimes I can be at Dnepr or Kiev. 
2) Are you sure it's key A? Quite unsure about that, there are LTE modems with Key B, but if it's key A it would be very easy to make this work on BCM84352Z
3)Stevezhengshiqi uses Key M > Key A or Key E
4) PCIList is just for beauty purposes and not actually injecting anything.

**Comment by influenist** [comment]
@PavelLJ updated my comment just before. Sorry about the country mixup. Im from NL (Amsterdam) myself but live now 5 years in Warsaw. LTE is m.2 key B. offers all the lanes which we need, and if you are lucky, the port is still there in your NB Pro. Newer rev do not have the port. 

I'm sure the port is not M.2 as you can see here. Also not mini pci-e. See: 
![11c0694433e7a38fde53b08e0a62ee47](https://user-images.githubusercontent.com/22964559/40512699-e83e8c50-5fa3-11e8-958e-f049eb21b845.jpg)

**Comment by PavelLJ** [comment]
> and if you are lucky, the port is still there in your NB Pro. 

God, don't know about that. Still didn't disassembled mine as there is no need for that at the moment. I'm afraid I should check LTE port before I actually buy something.
>Sorry about the country mixup. Im from NL (Amsterdam) myself but live now 5 years in Warsaw

Hey, all is ok :) Warsaw is great!

> I'm sure the port is not M.2 as you can see here. Also not mini pci-e. See:

What the hell that port is then? My guess it's mPCIe, but idk, you should check that under Linux. I'm very interested in key B as [of PCI-SIG specs](https://pcisig.com/specifications/pciexpress/M.2_Specification/) (search m.2 on page) there is PCIe and USB, logic ports that are needed for WiFi+BT. There is a problem, PCIe lanes on laptops are not infinite, and Key B port specs is up to vendor as documentation says, so maybe it was disabled to give M.2 key M 4xPCIe logic lanes. We need investigate that a lot deeper, it's very interesting!

**Comment by stevezhengshiqi** [comment]
@influenist That will be really nice if a splitter cable can work. I will check my computer 8 hours later since I left it home.

**Comment by PavelLJ** [comment]
@influenist Found that strange type of connector, it's 12+6 (also known as 18pin), here's the [adapter](https://www.amazon.co.uk/gp/aw/d/B073ZC2Z4M/ref=mp_s_a_1_23?ie=UTF8&qid=1527231051&sr=8-23&pi=AC_SX236_SY340_QL65&keywords=m.2+key+b+adapter&dpPl=1&dpID=41fozI5-XCL&ref=plSrch). Now I hope I got 18pin and not WLAN_LTE lol

**Comment by influenist** [comment]
@PavelLJ please see @stevezhengshiqi his post. 

In NB Pro and NB Air there is a M.2 key slot. The adapter from Wdxxfu transforms this to the (18 pin) form factor (Apple module I guess) shown in my previous picture.

@daliansky could we setup a Gitter room for talks like these?

**Comment by PavelLJ** [comment]
@influenist I knew that, there was misunderstood about second revision, I thought there is 18pin in second revision but as you declared that's an adapter, now I understand. I try to find the way to fully use WLAN_LTE port, even without knowing about  presence of it in my laptop. If there wouldn't be one, I'll buy Key M > Key A and will play around splitter for internal BT, but now I hope I have WLAN_LTE (Key B) with USB and PCIe, and then I'll try to make an adapter Key B > Key A/E

**Comment by stevezhengshiqi** [comment]
@influenist It’s exactly the same. Could you sent a link of the splitter cable? I want a relaible one.

**Comment by influenist** [comment]
@PavelLJ the M.2 Key M to M.2 Key A+E does not work. So save your money

@stevezhengshiqi there is not just a "splitter cable" available. We need to make a pin-out of this connector to determine which pins we need to use.

// Off topic
@daliansky @stevezhengshiqi I just added my Git repo. Which is quiete similar to your build. As my intention is to make an effort for wide MacOS support on Xiaomi Mi laptop series (Notebook and Gaming). Lets discuss on gitter, wechat or skype how we can merge the projects and kick of further to support Air 13.3 and gaming latop? My repo: https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS

**Comment by stevezhengshiqi** [comment]
@influenist Good idea. Personally, I recommend to open a new branch for other devices since Air has some different methods and devices in DSDT. For example, in Xiaomi Air 6500u's DSDT, there's an embedded control(EC), which Pro does not have. So in the config.plist, we need to rename EC0 for Air 6500u.

I also prefer "clean install", meaning that all the hotpatches and renames are useful. If more hotpatches are merged, the EFI folder may become "gross".  So I think a new branch is good.

**Comment by PavelLJ** [comment]
Hey guys, today I was bored as I needed to prepare for exams, so I did anything not to prepare for exams. Nevermind. I played around UEFI BIOS today and got interesting results. Here is the list of hidden variables that can be installed via H20 UEFI Variable Editor (H2OVUE), see attachment. Full PCIe settings, fan control, undervolting and a lot, lot more... Here you go.
[IFR.txt](https://github.com/daliansky/XiaoMi-Pro/files/2041930/IFR.txt)
BTW it's just a list of variables, for successfully change it you need to rewrite NVRAM dump via H2OUVE, for this you need the dump itself. I'll attach the original one. 
[vars.txt](https://github.com/daliansky/XiaoMi-Pro/files/2041932/vars.txt)
P.S Remember, that is HEX value and it should be changed properly.
Cheers!

**Comment by influenist** [comment]
Update on the wifi module:

At this point we need to figure out which color is D+ and which color is D-. After the module should work by connecting to this interface. Wdxxfu has already the connector in stock, so only the color / pin for D+ and D- are important.

D+ and D- needed to determined by a multimeter. 

Has anyone has knowledge on this matter?

**Comment by PavelLJ** [comment]
@influenist Any updates on this? Maybe I'll disassemble my laptop tomorrow or so, so I can do something you need. What exactly I need to check?

**Comment by stevezhengshiqi** [comment]
Finally, I successfully solder my BT to WLAN pin 4 and 5. Pin 4 is D+ and Pin 5 is D-. I tried several times; and it is really difficult for a new beginner like me.
![img_20180531_190259](https://user-images.githubusercontent.com/36894554/40855793-306a02ce-6608-11e8-9f49-3511dfb4415f.jpg)
![img_20180531_190317](https://user-images.githubusercontent.com/36894554/40855807-3e925da6-6608-11e8-92a7-1a1f6cebc856.jpg)

**Comment by PavelLJ** [comment]
@stevezhengshiqi impressive! Any thought about Key.A/E+USB low profile adapter? CS2 which is 12+6 pin connector is used in MacBook Air 2013 and may be dropped quite soon...

**Comment by stevezhengshiqi** [comment]
> Is this BCM94360CS2 and all is working out of the box?

Yes, it's BCM94360CS2 and Wi-Fi function is working perfectly. Currently, I am struggling with bluetooth because bluetooth won't work after sleep. Maybe it's due to my settings

> When did you bought the laptop? I'm afraid there is no WLAN_LTE port on mine, still didn't checked.

I bought my laptop at Nov, 2017. All these laptops should have WLAN_LTE, no need to worry.

> Where can I contact with Wdxxfu? Is his adapter low-profile and fits under case without any problems?

I use Taobao(https://item.taobao.com/item.htm?spm=a1z09.2.0.0.6d3b2e8dK7sNkk&id=532197802538&_u=22diegp9f1ed) to connect him. He didn't have ebay or amazon links. My adaptor have some problems about screw. In order to attach the adaptor reliably, I use one of the screw inside the laptop, which won't cause much negative effects.

**Comment by PavelLJ** [comment]
> Maybe it's due to my settings

My guess it's all about SSDT_UIAC port type, try to change it to internal.

> All these laptops should have WLAN_LTE, no need to worry.

Ah okay, i thought there is some revisions of the laptop so i was little upset about it.
Thanks for link!

**Comment by stevezhengshiqi** [comment]
Actually when I bought the adaptor, there's no package three. What I am using now is package two. I have to ask seller for more information about third package.

**Comment by PavelLJ** [comment]
> Android File Transfer can also cause bluetooth sleep problems.

LOL HOW? By the way, ordered the adapter, so I think i'll have native Wi-Fi+BT in three weeks or so.

**Comment by stevezhengshiqi** [comment]
> LOL HOW? By the way, ordered the adapter, so I think i'll have native Wi-Fi+BT in three weeks or so.

Good for you. 
I corrected my USB settings and the problem didn't gone. Then I searched for a few posts and found this one https://www.tonymacx86.com/threads/bluetooth-bcm20702a0-problem-usb.185785/#post1200910 . So I tried and worked for me.

**Comment by influenist** [comment]
@stevezhengshiqi you need to DSDT patch ( hotpatch preferable in the acpi build) to disable your intel BT as per recommendations otherwise you will keep having BT issues.

**Comment by stevezhengshiqi** [comment]
@influenist I am pretty sure that I have done all these things. After removing Andriod File Transfer, my BT sleep problems never come back.

**Comment by PavelLJ** [comment]
@stevezhengshiqi sorry, can I have full photo of how you placed the cables and third antenna (if you have it)? I got the adapter, but now I need to dance around BIOS a bit to rip off that ugly DVMT hack, so I have time to put cables right. Any suggestions?

**Comment by stevezhengshiqi** [comment]
@PavelLJ Sorry, I don't have a full photo, and I can't take picture of it since I am restricted in campus. I come back home in three weeks.

HINT: To make BT work, you need to solder the red cable to PIN4 and orange cable to PIN5.

**Comment by stevezhengshiqi** [comment]
@PavelLJ Finally, I have chance to take a photo of my device. Here it is.
![photo](https://user-images.githubusercontent.com/36894554/43049116-eec7d82e-8e24-11e8-8e5b-453286b30bd3.jpg)

**Comment by Neolo** [comment]
If you use adapter like below, soldering BT pins to LTE socket **DOEN'T ENABLE BT. Tested using Windows, no hardware detected, besides WiFi part**! This adapter is missing something, probably it doesn't power up the BT chip. So don't waste your time. And the adapter from stevezhengshiqi's picture is not available for international buyers, some custom stuff made by some unknown Wdxxfu Studio.

![40491034-5a4f045a-5f6d-11e8-83fc-5326a100f92c](https://user-images.githubusercontent.com/2836790/43555911-00568510-95cb-11e8-88a4-f0a4acb91fd0.jpg)

**Comment by Neolo** [comment]
And for God's sake, don't use tape to hold the chips, use for wires only.

**Comment by PavelLJ** [comment]
@Neolo LOL, I'm living in Belarus which is far more unreachable from China but I bought it from TaoBao without any problems at all. By the way I still didn't solderied bluetooth, my soldering instruments are too thick for that

**Comment by Neolo** [comment]
@PavelLJ, they don't ship to US. Yes, such a "lol".
http://www.howtotao.com/china-taobao-prohibited-items/

![screen shot 2018-08-02 at 6 05 03 am](https://user-images.githubusercontent.com/2836790/43577513-09ab06fa-961a-11e8-94a5-289c7a9e33e9.png)

**Comment by Neolo** [comment]
![screen shot 2018-08-02 at 4 10 44 pm](https://user-images.githubusercontent.com/2836790/43608444-15d304e6-966f-11e8-9dd5-b98cda775df3.png)

Voila!

**Comment by PavelLJ** [comment]
@Neolo by the way mine doesn't "make a bulge" too. Also, it uses 12+6(18pin) Apple WiFi card, it's not PCIe

**Comment by shilch** [comment]
Hey, can somebody give a quick summary of what to do to enable WIFI+BT on Xiaomi Notebook Pro?  
I ordered one a few days ago an expect to receive it in a few weeks but would like to order all the pieces that I need to enable WIFI+BT (because shipping this hardware will take some time as well).  

@stevezhengshiqi You said that you bought a BCM943602CS instead of a BCM94360CS2. What's the difference between the two? I know that the latter is the older chip but why is it still sold by the merchant on Taobao? Is there any advantage of using BCM94360CS2 over BCM943602CS?  

So if I have received the adapter + chip, do I just need to plug it into the second M.2 slot, disconnect the cables from the Intel chip and connect it to the new chip, and solder the Bluetooth wires? Or is there more stuff to do?  

Thank you in advance!

**Comment by Recreabox** [comment]
Like some people i ordered the green adapter like @Neolo and the DW1830A Chip (Wifi + Bluetooth).
I don't tested yet cause i don't have the MHF4 cable yet.

But i have a question, if i buy the black adapter of @stevezhengshiqi will i be able to make works the bluetooth of my chip by soldering to the WLAN port ?
