### ISSUE TITLE
Audio no devices

### ISSUE THREAD

**Issue by pakli2** [daliansky/XiaoMi-Pro#32]
Below are my mi notebook pro spec:-

Hardware: i7-8550U 16GB ram 256GB ssd and BIOS 502
OS version: 10.13.5 High Sierra

Based on IORegExplorer, CodecVendorID = 0x10ec0298 (which is normal) but CodecRevisionID is 0x100101 (which is different from 0x100103). Will this affect the AppleALC ALC298? Please help.

**Comment by PavelLJ** [comment]
Sound works just fine for me, same configuration.

**Comment by pakli2** [comment]
Are you on High Sierra 10.13.5 as well? Did you upgrade from 10.13.x or a fresh install of 10.13.5?

**Comment by PavelLJ** [comment]
Yeah, absolutely same setup as your. I just updated it via App Store

**Comment by pakli2** [comment]
Not same. mine was fresh install of 10.13.5. I need to find 10.13.4 installer to test if sound works, and then upgrade 10.13.5 then. Any pointer?

**Comment by pakli2** [comment]
Got it working now after AppleALC added support for codec revision id 0x.100101
