### ISSUE TITLE
ELAN fingerprint scanner

### ISSUE THREAD

**Issue by Neolo** [daliansky/XiaoMi-Pro#37]
Anything about ELAN fingerprint scanner in Xiaomi Pro? 
Not sure if model the same, but they just marked it "solved" without any obvious solution written
https://www.tonymacx86.com/threads/solved-asus-ux430ua-fingerprint-trackpad-touch-id.230671/page-3

**Comment by stevezhengshiqi** [comment]
Please don't open issue that never gonna happen. Apple have its own security fingerprint sensor hardware. The third party will never be supported. (If our ELAN fingerprint sensor can work and send data to Apple database, I will be really disappointed with Apple's effort on their fingerprint security)

Only solution to make our fingerprint work is that ELAN released a third party software on MacOS.

**Comment by Neolo** [comment]
What database you talking about? Where did you get such information? lol

**Comment by stevezhengshiqi** [comment]
@Neolo Please re-read my reply. I have edited it before your reply.
