### ISSUE TITLE
Touchpad gestures (again) 

### ISSUE THREAD

**Issue by Neolo** [daliansky/XiaoMi-Pro#38]
Touchpad gestures are pretty terrible, especially scrolling and double-finder tap, not even saying about the rest of swipes, which are just not working. Tried all Voodoo kexts I found, they are all more or less terrible, but none of them good for daily usage.
Found this topic, can it be used? https://osxlatitude.com/forums/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/ 
It seems doesn't pickup Xiaomi's touchpad model at all.

**Comment by stevezhengshiqi** [comment]
I post a video of the trackpad in my release. In my opinion, it's working great on two finger scrolling and other gestures. If you have other good trackpad drivers, welcome to share.
(I believe there's no other better kexts on the website, maybe you have to take it if the current one doesn't suit you.)
[TrackPad Gestures.mp4.zip](https://github.com/daliansky/XiaoMi-Pro/files/2174714/TrackPad.Gestures.mp4.zip)

**Comment by Neolo** [comment]
You have to test it during the web browsing, and you’ll see how scroll gets locked in, even after you already removed your fingers from the track pad. Short video is not a test.
Right click responds bad (either extra reaponce, or no responce at all). Try to put your hand with an angle on a track pad, you you’ll see how bad is it, unusable.

**Comment by pqml** [comment]
SmartTouchpad is a PS2 Controller, it will not work for the Mi Pro trackpad since it use an I2C Trackpad. SmartTouchpad is used in the EFI folder only for the keyboard support.

VoodooI2C is the best you can have right now. 
Latest commit from @hieplpvip fork seems to fix your right click issue a bit :
https://github.com/hieplpvip/VoodooI2C

Native branch from VoodooI2C will be a big improvement for scrolling and multitouch but it's not actively developed right now

**Comment by Neolo** [comment]
@pqml If I remove appleps2smarttouchpad.kext and leave only VoodoI2c.kext, it stops working completely. Also what's VoodooI2CELAN.kext and VoodooI2CUPDDEngine.kext for? I guess this is exactly for gestures, but to enable these drives?

**Comment by pqml** [comment]
VoodooI2CELAN.kext doesn't work for the Mi Notebook Pro. Use VoodooI2CHID Instead. 

Don't know about VoodooI2CUPDDEngine, I've never used Touch Base's UPDD because the base software is too overpriced for me (See http://touch-base.com/prices.asp for more infos)

**Comment by Neolo** [comment]
I don't get it, you have to buy those drivers in order to use VoodooI2CUPDDEngine ?

**Comment by stevezhengshiqi** [comment]
If you aren't satisfied with current driver, you can replace it. However, I am not going to change it since it's almost prefect for me.

**Comment by pqml** [comment]
>  I think Voodoo doesn't put much efforts into open source driver i2c and keeps it with limited functionality, just because of this "partnership" with touch-base. They probably pay them for bringing customers.

alexandred put a lot of efforts into VoodooI2C. The v2 is already much better than the first one, and he continues to help people on the gitter, for free. 

There is absolutely zero partnership with Touch Base. VoodooI2CUPDDEngine is also not the most used kext satellite and it's not even maintained by the main collaborators of VoodooI2C / VoodooI2CHID / VoodooI2CELAN.

**Comment by Neolo** [comment]
Put 2 finger, scroll, lift one finger (either one) and try to move the pointer - stuck in scroll mode. Lift the second finger and put it back and try to move the pointer - and it's still in scroll mode. To get out of this trap, you have to put 2 fingers again and lift them together.
And no need for any youtube videos.

**Comment by stevezhengshiqi** [comment]
@Neolo Thank for reply. Just then I tested again; and scroll mode works perfect. I have no issue like what you described. Are you sure your are using the EFI folder(05-16-2018) in my release? If you want, can I have a look on your EFI folder?
[Two Finger Scroll Test.mp4.zip](https://github.com/daliansky/XiaoMi-Pro/files/2189667/Two.Finger.Scroll.Test.mp4.zip)
