### ISSUE TITLE
Problems with updates

### ISSUE THREAD

**Issue by jknvv13** [daliansky/XiaoMi-Pro#4]
Cannot update to 10.13.2 because of LiLu.Kext not updated. But the problem also goes to modified Intel Graphics Kexts and IDs that prevent it booting, maybe FakePCIID and IntelGraphicsFixup.
Also, VoodooI2C was updated yesterday, and another current problem is that there are no keys to use the brightness up/down.

**Comment by daliansky** [comment]
The updated EFI has solved the 10.13.x installation issue and also updated the VoodooI2C driver, which brings a good touch experience.
Brightness key You can try using an external keyboard to adjust shortcuts.
