### ISSUE TITLE
USB C Speed 2.0

### ISSUE THREAD

**Issue by johnnync13** [daliansky/XiaoMi-Pro#43]
the usb type C not have the correct speed.
I don't have this laptop, but I follow and help a Spanish community in Telegram.
It is possible that you try to fix with https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/ and https://www.tonymacx86.com/threads/guide-usb-power-property-injection-for-sierra-and-later.222266/
Thank your for your all work

**Comment by stevezhengshiqi** [comment]
@johnnync13 If you are using my [release](https://github.com/stevezhengshiqi/XiaoMi-Pro/releases), you will have full speed type C.

**Comment by johnnync13** [comment]
The Spanish community will be super grateful. I do not have money to buy this laptop but if I have knowledge about hackintosh, I have tried to contribute as much as possible, thanks to people who use beta-testers.
