### ISSUE TITLE
Booting problem EFI v1.2.3

### ISSUE THREAD

**Issue by MikitaKurlovich** [daliansky/XiaoMi-Pro#45]
Hi! Can't boot with EFI v1.2.3.
The progress bar is blinking from the beginning and on the 60% restarts the laptop.
Who knows where is might be a problem?

High Sierra 10.13.5 (EFI 1.2.2)
Mi Notebook Pro 15.6 i7 / 16GB with factory BIOS firmware.

**Comment by stevezhengshiqi** [comment]
@MikitaKurlovich Make sure you delete `BOOT` and `CLOVER` folders and then copy them from the pack in release page. If you don't mind, can I have a look at your CLOVER folder?

**Comment by MikitaKurlovich** [comment]
I'm sure absolutely. I did it 3 times. First time from the Clover Configurator and after that in win10 (Explorer++) 
After that, I tried to make changes separately (update kexts which works before with the same names) but there is the same problem.

Now my BOOT and CLOVER folder similar like in EFI v1.2.2. Is it will be useful for you?

I decided to update my EFI because I have a problem with HDMI output. When I plug in external monitor my laptop monitor turns black and does not change after disconnecting the HDMI cable.

**Comment by stevezhengshiqi** [comment]
HDMI problem can be solved by close the lid for a few seconds and reopen it. I will restore my device to 10.13.5 to check whether if it works or not.

**Comment by MikitaKurlovich** [comment]
@stevezhengshiqi I can update my macOS to 10.13.6 and will try again.

**Comment by MikitaKurlovich** [comment]
One more question about 3.5 audio output. Is it work correctly? I hear only noise...

**Comment by stevezhengshiqi** [comment]
I think 3.5 audio output is all about `CodecCommander.kext` and `SSDT-ALC298_XiaoMiPro`, which I haven't made any changes yet. `CodecCommander.kext` has to be put in /L/E and rebuild the kextcache.

**Comment by MikitaKurlovich** [comment]
So… I tried to update to the 10.13.6 from the App Store and at the 60-65% I got a error. Now I can’t boot Mac :/

**Comment by stevezhengshiqi** [comment]
I think it's because the removal of `IntelGraphicsDVMTFixup.kext`. I will put it back in my 1.2.3 release.

**Comment by richardchien** [comment]
I encountered the same problem when installing daliansky’s 10.13.6 image using the latest v1.2.3 EFI release. It keeps restarting at about 60%. I tried both removing EFI then copy, and overriding, but neither worked. After I switch to the 5-14  release and 10.13.4, the problem gone.

BTW, if I keep using the 5-14 release, can I upgrade the system to 10.13.6 through Mac App Store?

**Comment by richardchien** [comment]
@stevezhengshiqi Thanks a lot! I will try it later.
