### ISSUE TITLE
Lag HD graphics + touch pad 

### ISSUE THREAD

**Issue by FlymeDllVa** [daliansky/XiaoMi-Pro#48]
Put the latest release EFI on 10.13.6. The problem is: the graphics lag with more complex animations. Drag and drop Windows, 3D graphics, etc.. Xiaomi is with i7 on 603 BIOS. Video: 
https://www.youtube.com/watch?v=f23DyPI4Z4U&feature=youtu.be

The touchpad is not always a click

**Comment by stevezhengshiqi** [comment]
Hi, I just played the chess game and no problem here. Maybe you can try to run `Kext Utility.app` to clean the kextcache and kill background apps. The [graphics driver](https://github.com/acidanthera/WhateverGreen) and [trackpad driver](https://github.com/hieplpvip/VoodooI2C/tree/native) are the newest.

**Comment by FlymeDllVa** [comment]
Touch pad: https://www.youtube.com/watch?v=P7xq-hX_JLw&feature=youtu.be
Graphics: https://www.youtube.com/watch?v=_Q6VmusUvK4&feature=youtu.be
Of course I used the Kext Utility.app, but it did not produce results. Any ideas on how to deal with micro-lags and touchpad?

**Comment by FlymeDllVa** [comment]
And did not come up with how to solve the problem with lag graphics. How to contact vit9696?

**Comment by stevezhengshiqi** [comment]
Try to discuss in this forum: https://www.insanelymac.com/forum/topic/325987-whatevergreen-support-topic/ .
