### ISSUE TITLE
有完整安裝敎學嗎

### ISSUE THREAD

**Issue by carlhung** [daliansky/XiaoMi-Pro#5]
有完整安裝敎學嗎？
謝謝

**Comment by daliansky** [comment]
可以瀏覽：[macOS安裝教程兼小米Pro安裝過程記錄](https://blog.daliansky.net/MacOS-installation-tutorial-XiaoMi-Pro-installation-process-records.html)
也可以進入QQ群討論：247451054 [小米PRO黑苹果高级群](http://shang.qq.com/wpa/qunwpa?idkey=6223ea12a7f7efe58d5972d241000dd59cbd0260db2fdede52836ca220f7f20e)
