### ISSUE TITLE
Windows 10 won't boot

### ISSUE THREAD

**Issue by paajake** [daliansky/XiaoMi-Pro#52]
Windows 10 doesn't boot from the clover boot menu, it always gives a blue screen unless I set the windows 10 as first boot device, then it works.
![img_20180807_233304](https://user-images.githubusercontent.com/12656820/43818339-a5c63426-9acd-11e8-93e8-abe9e58b936c.jpg)

**Comment by stevezhengshiqi** [comment]
I think it's a Clover related problem. You can create a ticket and send your troubleshooting file to https://sourceforge.net/p/cloverefiboot/tickets/, or you can install an older version of Clover.

**Comment by paajake** [comment]
I would appreciate a link to read on how to do the clover install, I don't have experience with hackingtoshs this is my first and I followed a simple guide which only mentioned copying the efi folder to the efi drive.

**Comment by paajake** [comment]
The windows boot files were missing on the windows efi partition, I got it fixed

**Comment by Vichearith** [comment]
Hello !
I have the same issue. How did you resolve it ?

**Comment by Vichearith** [comment]
I put back Windows at first in the boot order and it worked back. The problem is that now, i have to do F12 to choose to launch MacOS

**Comment by stevezhengshiqi** [comment]
@Vichearith Please read FAQ part in README
