### ISSUE TITLE
Problem with touch pad in 15.6 in Mac OS 10.14

### ISSUE THREAD

**Issue by seftandshelby** [daliansky/XiaoMi-Pro#57]
problems with the touchpad - it works in MAJAVE (beta) bad
1 hang when scrolling to the lunchpad
2 when scrolling pages on the Internet
  while in version 10.13.3 I have a perfect touchpad and hide it quickly and smoothly)
Does anyone have such a problem?

**Comment by seftandshelby** [comment]
https://youtu.be/I2sGpkBPprY

**Comment by stevezhengshiqi** [comment]
Hi, the trackpad in Mojave do have problems. According to what [alexandred](https://github.com/alexandred/VoodooI2C) said in (gitter)[https://gitter.im/alexandred/VoodooI2C]

> yes when mojave releases and I install it, I will add a fix to the main release
the fix 
in the github [issue](
https://github.com/alexandred/VoodooI2C/issues/70) works but isnt suitable for everyday use

, I think we have to wait until the final release of Mojave. I suggest that you can visit the GitHub(https://github.com/alexandred/VoodooI2C) of the trackpad driver to check if there's a new version release.

**Comment by seftandshelby** [comment]
Thanks to information 😊
