### ISSUE TITLE
trackpad gestures problem

### ISSUE THREAD

**Issue by FunnyDevs** [daliansky/XiaoMi-Pro#58]
Hi! I have installed macOS high Sierra on my Xiaomi notebook pro. I have no problem except for trackpad gesture: I am not able to pich to zoom and use 3 fingers to show desktops app (2 fingers scrolling and 3 fingers swipe full screen apps works)

**Comment by stevezhengshiqi** [comment]
Hi, for more trackpad gestures, you can try v1.2.6 in my [release page](https://github.com/stevezhengshiqi/XiaoMi-Pro/releases). The gestures there are similar to real Mac.

**Comment by FunnyDevs** [comment]
Hi. I have tried v 1.2.6 a now pinch to zoom works.
4 fingers gestures is unusable. 3 fingers swipe up doesn't work but i have seen from your video that It should be work. Any suggestions?

**Comment by stevezhengshiqi** [comment]
If your are using v1.2.6, all the gestures in `System Information.app - Trackpad`should work. My suggestion is to check whether `BOOT` and `CLOVER` folders are replaced completely and also to make sure no other kexts are installed in S/L/E or /L/E.

**Comment by FunnyDevs** [comment]
Ok, i have deleted now (instead of replacing the 2 folders) and the gestures work! Only the show desktop gesture (4 fingers) work not very well ( I hope there will be an update in the future!). Thanks!

**Comment by stevezhengshiqi** [comment]
You are welcome. More trackpad information can be accessed at https://github.com/alexandred/VoodooI2C.
