### ISSUE TITLE
i can't install mojave on xiaomi notebook pro with the latest efi 

### ISSUE THREAD

**Issue by JenvyXU** [daliansky/XiaoMi-Pro#59]

**Comment by stevezhengshiqi** [comment]
Hi, you can try to use the latest release version in my repository [here](https://github.com/stevezhengshiqi/XiaoMi-Pro/releases), and make sure the `BOOT` and `CLOVER` folders are replaced completely.

**Comment by JenvyXU** [comment]
@stevezhengshiqi  At first, thanks for you help,I have installed the Mojave successfully with you efi, but there is another problem,display will go something wrong when i use hidpi（就是开启hidpi时候会屏幕有点花屏，在默认的分辨率下不会有这种情况），do you have any solution

**Comment by stevezhengshiqi** [comment]
Hidpi 在mojave环境下不是很稳定，你可以咨询脚本作者(https://github.com/xzhih/one-key-hidpi)来获取解决办法。

**Comment by stevezhengshiqi** [comment]
I decide to close this issue. You can open a new issue at this repository or https://github.com/xzhih/one-key-hidpi, which is highly recommended.
