### ISSUE TITLE
耳机无声

### ISSUE THREAD

**Issue by XdpAreKid** [daliansky/XiaoMi-Pro#6]
耳机无声，或是输出的声音为微弱的电流声，听不到声音

**Comment by daliansky** [comment]
请更新声卡驱动程序，同时请入注id:99

**Comment by kvn1351** [comment]
@daliansky @XdpAreKid I got it working after running the .command script in the `ALC298_id99_CC_ALCPlugFix/ALCPlugFix` folder.

**Comment by daliansky** [comment]
https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html
15.其它问题
