### ISSUE TITLE
Kernel panic after user login

### ISSUE THREAD

**Issue by zjkyz8** [daliansky/XiaoMi-Pro#606]
Guys, I use OC and update MAC OS recently. From then on, every time I login system MAC kernel panic. Mac safe mode is ok.
Below is the snapshot of panic report 
![aac7cf57ffa4d51ddf37972cee8b355f](https://user-images.githubusercontent.com/1856389/136766274-9f3d482f-8140-4abe-bb36-5c9bbb57ae47.png)

I dont not whether this is a EFI related issue，it is seems caused by skyguard kext. Does anyone has idea about this?

**Comment by zjkyz8** [comment]
Thank you very much, I found them, All I need to do is delete those folders and run "sudo kextcache -i"?  Is there any other thing i need to do?

**Comment by stevezhengshiqi** [comment]
You need to delete kexts that related to skyguard in /Library/Extensions, don't delete the whole folder. And the command should be `sudo kextcache -i /.`

**Comment by stevezhengshiqi** [comment]
Close as it's a user space problem.

**Comment by zjkyz8** [comment]
That works for me, thank you
