### ISSUE TITLE
Ve have a big problem in last  config 

### ISSUE THREAD

**Issue by seftandshelby** [daliansky/XiaoMi-Pro#61]
we have a big problem with the last config I would recommend the penultimate, since the graphics engine is not working properly and a lot of friezes are periodic 2 we can not be in Intel uhd 2000 megabytes so we only have Intel 1500 megabytes.

**Comment by stevezhengshiqi** [comment]
Hi, I am agree with your idea. The change of VRAM is useless and causes unexpected glitches. I will change it in my github later.

**Comment by stevezhengshiqi** [comment]
Removed `framebuffer-unifiedmem` in `config.plist`.
