### ISSUE TITLE
2lc 

### ISSUE THREAD

**Issue by seftandshelby** [daliansky/XiaoMi-Pro#62]
Pleas check, 2lc for 10.14 , and sai mi how work this kext on 10.14 . https://github.com/alexandred/VoodooI2C/releases

**Comment by stevezhengshiqi** [comment]
@seftandshelby Hi, thanks for information. It's a I2C. But the version 2.1.1 is not working better than 2.0.1 in this GitHub, and I am not going to update. 

If you want tot try it on 10.14, I edited the source code to let it work on 10.14. For more information, you can visit my reply in https://github.com/alexandred/VoodooI2C/issues/70.
