### ISSUE TITLE
Jeck problem with alc fix

### ISSUE THREAD

**Issue by seftandshelby** [daliansky/XiaoMi-Pro#63]
very frequent problems with the 3.5 mm jack, fixes do not help, I have one problem with Jack and the inability to fix alc?

**Comment by stevezhengshiqi** [comment]
@seftandshelby Hi, can you run `install.command` again from [ALCPlugFix](https://github.com/stevezhengshiqi/XiaoMi-Pro/tree/master/ALCPlugFix) folder and take a screenshot for me? I want to make sure you have installed successfully. Also make sure you are using the latest release.

**Comment by seftandshelby** [comment]
<img width="611" alt="2018-09-23 4 35 19" src="https://user-images.githubusercontent.com/42048337/45923274-8a7ef180-beea-11e8-817c-c3c1d6a448b0.png">
 yes I use actually version alc

**Comment by seftandshelby** [comment]
stevezhengshiqi- thanks for the sympathy, I rebooted the operating system and it earned))) the topic can be closed, just write in the instructions that requires a reboot!

**Comment by stevezhengshiqi** [comment]
Congratulations. I will add that in README later.

**Comment by stevezhengshiqi** [comment]
@seftandshelby Added. I am going to close this issue.
