### ISSUE TITLE
MacOs13 Compatibility?

### ISSUE THREAD

**Issue by Giannidmg** [daliansky/XiaoMi-Pro#666]
Hello, reading the EFI 1.6.6 release changelog, it turns out that it is not compatible with the new macOS 13, why?

**Comment by stevezhengshiqi** [comment]
- `OpenCore`v0.8.1 's `AvoidRuntimeDefrag` is broken on macOS13. Users have to disable this when upgrading, which is not recommended in OpenCore's manual
- `AirportItlwm` does not support macOS13, which means no Wi-Fi. Users can use itlwm + Heliport instead.
- And more...

For further macOS13 support, please ask [Acidanthera](https://github.com/acidanthera) and kext developers listed in [Credits](https://github.com/daliansky/XiaoMi-Pro-Hackintosh#credits) . When they distribute stable kexts for macOS13, then that's the time we support macOS13.

**Comment by stevezhengshiqi** [comment]
For anyone who is interested in Ventura support, https://github.com/daliansky/XiaoMi-Pro-Hackintosh/actions/runs/2480614723 is the latest EFI version that should support macOS13.

**Comment by Giannidmg** [comment]
> For anyone who is interested in Ventura support, https://github.com/daliansky/XiaoMi-Pro-Hackintosh/actions/runs/2480614723 is the latest EFI version that should support macOS13.
> **ALWAYS BACKUP!**

Is it enough to update via ota to install macOS 13?

**Comment by Giannidmg** [comment]
> For anyone who is interested in Ventura support, https://github.com/daliansky/XiaoMi-Pro-Hackintosh/actions/runs/2480614723 is the latest EFI version that should support macOS13.
> **ALWAYS BACKUP!**

I tried to update via OTA but the installation starts crashes here
![Uploading 272F4D8B-E849-4E9B-9058-7A999EEBAC4B.jpeg…]()

**Comment by Giannidmg** [comment]
> For anyone who is interested in Ventura support, https://github.com/daliansky/XiaoMi-Pro-Hackintosh/actions/runs/2480614723 is the latest EFI version that should support macOS13.
> **ALWAYS BACKUP!**

I tried to update via OTA but the installation starts crashes here
![Uploading DC697387-23D2-47D9-B0C4-EFC6F3A53820.jpeg…]()

**Comment by stevezhengshiqi** [comment]
> I tried to update via OTA but the installation starts crashes here

Image is not shown here.

**Comment by Giannidmg** [comment]
![Uploading A8A76782-775B-4B7F-8D5F-A8AFAE928244.jpeg…]()

**Comment by Giannidmg** [comment]
> > I tried to update via OTA but the installation starts crashes here
> 
> Image is not shown here.

fix it

**Comment by stevezhengshiqi** [comment]
@Giannidmg It looks like you are still using the old EFI. Did you use the latest EFI in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/actions/runs/2480614723?

**Comment by HKMV** [comment]
> @Giannidmg It looks like you are still using the old EFI. Did you use the latest EFI in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/actions/runs/2480614723?

我也是通过OTA,配置完成后重启进入安装过程就卡住不动了,使用的是最新的EFI

**Comment by stevezhengshiqi** [comment]
@HKMV 请详细说明安装过程卡住不动或者截图。

**Comment by Giannidmg** [comment]
> @Giannidmg It looks like you are still using the old EFI. Did you use the latest EFI in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/actions/runs/2480614723?

I used this EFI and I have on the block mentioned above, both OTA and with USB installer

**Comment by HKMV** [comment]
> 

我进入原来的系统,它自动还原了,我再装下看下,请问oc是那个配置控制显示日志的呢?

**Comment by HKMV** [comment]
> @HKMV 请详细说明安装过程卡住不动或者截图。

![IMG_20220612_204513.jpg](https://user-images.githubusercontent.com/26456469/173233813-2877c057-0160-4d09-b84c-de5391ead7ad.jpg)

**Comment by stevezhengshiqi** [comment]
Not sure about the exact reason. From the error log, I suggest changing `DmgLoading` from `Signed` to `Any`.

**Comment by Giannidmg** [comment]
dopo aver avuto questo errore

> > > I tried to update via OTA but the installation starts crashes here
> > 
> > 
> > Image is not shown here.
> 
> ![IMG_1537 Large](https://user-images.githubusercontent.com/45434724/173231051-38fb4df2-5e25-4e66-b814-ef2f116869fe.jpeg)

Il mio mi notebook non trova più la partizione EFI nel bios, essa esiste, non è vuota, ma mi trova solo windows boot manager tra le entry di boot

**Comment by Giannidmg** [comment]
> Not sure about the exact reason. From the error log, I suggest changing `DmgLoading` from `Signed` to `Any`.

Same mistake also with this change

**Comment by stevezhengshiqi** [comment]
@Giannidmg OpenCore has new comments that may fix the issue, please try https://github.com/daliansky/XiaoMi-Pro-Hackintosh/suites/6908721734/artifacts/268323713

**Comment by Giannidmg** [comment]
There are issues using the latest EFI to upgrade to beta 3. It starts the installer appears the apple starts loading it freezes and restarts

**Comment by Giannidmg** [comment]
There are issues using the latest EFI to upgrade to beta 3. It starts the installer appears the apple starts loading it freezes and restarts
![Uploading 3C6ADCE3-35A3-4FB1-9663-C09DD669A088.jpeg…]()

**Comment by stevezhengshiqi** [comment]
> There are issues using the latest EFI to upgrade to beta 3. It starts the installer appears the apple starts loading it freezes and restarts

You need to update the latest OpenCore and Lilu manually. See https://github.com/acidanthera/OpenCorePkg/commit/bd2d3f29ab46534b3f72add4463e5b56a1549e3c and https://github.com/acidanthera/Lilu/commit/37e93c6e1af2bb1ec214013066d0c8043b3667f3
