### ISSUE TITLE
headphones on jack error

### ISSUE THREAD

**Issue by sebmoris** [daliansky/XiaoMi-Pro#67]
Hi, everyone :)
I have problem with headphones connected on jack. I used ALC fix plug, and nothing, 
example: when I reboot os I hear some quietly noises is not problem, its normal I think, impedance cable load every energetic noises from laptop but when I only run something app who's use sound card ... silent :) but when I used all Clover config and files by Lorenzo from Youtube about tutorial everything works fine... However, I would prefer to use your clover configuration because it gains over 1000 points on performance, which is a lot when working with different programs
Thx for help :)

**Comment by sebmoris** [comment]
https://www.youtube.com/watch?v=MVVuzXh42Wg
in informations about movie there is link do google drive witch clover directory :)

**Comment by stevezhengshiqi** [comment]
@sebmoris The CLOVER folder in the link above is actually an old version of this Github. Maybe the should put a credit in the video. I will study the code when I am free.

**Comment by sebmoris** [comment]
thx for help :)

**Comment by stevezhengshiqi** [comment]
@sebmoris There are two ideas I come up with. 
First, make sure you replug the earphone after every reboot. I don't have these kind of problems after replug.

Second, try to replace `EFI/CLOVER/kexts/Other/CodecCommander.kext` with the one below. Reboot and see whether it works, thx.
[CodecCommander.kext.zip](https://github.com/daliansky/XiaoMi-Pro/files/2410377/CodecCommander.kext.zip)

**Comment by stevezhengshiqi** [comment]
@sebmoria Good. So the correct fix is to replace the `CodecCommander` in the GitHub with the one I gave above?

**Comment by sebmoris** [comment]
i dont replace `CodecCommander`. Your solution about replug jack works :D 
thanks for help :)

**Comment by stevezhengshiqi** [comment]
OK.
