### ISSUE TITLE
NoTouchID with MBP15,2 SMBIOS

### ISSUE THREAD

**Issue by FallenChromium** [daliansky/XiaoMi-Pro#69]
Well, it's a week now since I installed Mojave with MBP15,2 and as far as I can tell, all works smooth. I had to install NoTouchID tho, mainly because of ton of BiometricKit errors. Can we have MBP15,2 SMBIOS in next build and can we ditch CPUFriend if we will switch to it?

**Comment by stevezhengshiqi** [comment]
I don't think MBP15,2 SMBIOS is a good idea, because CPUFriend will overwrite the SMBIOS PM file and macOS 10.13.5 doesn't support MBP15,2. If you want  MBP15,2 's power management, please replace archive in https://github.com/daliansky/XiaoMi-Pro/issues/53.
