### ISSUE TITLE
[Fixed][Waiting for implementaiton] Brightness keys aren't working

### ISSUE THREAD

**Issue by kvn1351** [daliansky/XiaoMi-Pro#7]
Please fix the brightness control, so that we can use the hardware keys to control it.

~~Everything else works great~~, thanks a lot!

OS version: 10.13.3

**Comment by gplast** [comment]
You can easily enable brightness keys by using the FN+F4 and FN+F5. You have to go to Settings->Keyboard->Shortcuts->Display and check Decrease/Increase display brightness. Double click next to Decrease/Increase display brightness and press FN+F4 / FN+F5. Now you can Control Brightness easily with these keys(I hope that helps).

**Comment by kvn1351** [comment]
@gplast Thanks a lot for your answer. I already knew of this workaround, you could also use BetterTouchTool to get it even nicer (without FN), but I wanted to file a report of this bug nonetheless. 

It's not a big issue, but it would be nice if it could get sorted.

**Comment by gplast** [comment]
Okay, i use BetterTouchTool to control play/pause but i will give it a try. Thank you.

**Comment by kvn1351** [comment]
I've managed to patch the ACPI to fix the brightness keys. However it's a static patch, i.e. a patched DSDT.aml. It works great and all, but it would be cool if I create a hotpatch of it instead.

I'm not experienced enough with SSDT hotpatching thoughk, so if there's someone who could help with some "External" declarations, please send me a message.

The patched method is huge and contains tons of references that have to be declared, I've fixed most of them, but some are still acting up..

Now I'll try to fix the HDMI issue.

**Comment by daliansky** [comment]
As for brightness keys, I tried changing the default keymaps (f14/f15) to f4/f5, and the brightness control is working as well. I can't quite tell the difference between these and the native keystrokes (fn+f4/f5). 
<img width="432" alt="qq20180203-224539 2x" src="https://user-images.githubusercontent.com/36077664/35775083-d61493ba-0979-11e8-918e-9c97df534070.png">
Appreciate you guys' hard work, thanks!
