### ISSUE TITLE
mi-book air hd520 7M

### ISSUE THREAD

**Issue by mission-young** [daliansky/XiaoMi-Pro#70]
我在2016款mi-book air上安装了macOS10.14，通过您的EFI配置成功启动，但显卡显示为hd520 7M，未能成功驱动。请问该如何调整？谢谢！

**Comment by stevezhengshiqi** [comment]
@mission-young 要调整config里的AAPL,ig-platform-id 和 device-id。我帮你把`59160000`调整为适合hd520的`19160000`，你可以试一下。
[config.plist.zip](https://github.com/daliansky/XiaoMi-Pro/files/2436722/config.plist.zip)

**Comment by mission-young** [comment]
好的，非常感谢！后来我用您网站上给的10.14的镜像，稍作调整config.plist文件之后，工作正常了~
附上mibook-air 2016的config.plist 文件。

[config.plist.zip](https://github.com/daliansky/XiaoMi-Pro/files/2452679/config.plist.zip)

**Comment by stevezhengshiqi** [comment]
感谢分享。镜像可能是由@daliansky 制作的，替你谢谢他的付出。
