### ISSUE TITLE
OC 编辑器 提示，配置文件 有三处错误。

### ISSUE THREAD

**Issue by 1457384613gh** [daliansky/XiaoMi-Pro#724]
OC 编辑器 提示，配置文件 有三处错误。
<img width="557" alt="截屏2023-05-14 10 52 53" src="https://github.com/daliansky/XiaoMi-Pro-Hackintosh/assets/69227436/0edaf765-1a65-467e-8333-669935b1a21c">

**Comment by abc99587758** [comment]
这个可以不用去管，或者你用oca可以自己修复

**Comment by abc99587758** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件已收到，我会尽快查阅，谢谢。

**Comment by stevezhengshiqi** [comment]
@1457384613gh 你是用的验证器并非官方OpenCore，而是mod版。官方OpenCore并没有EnableForAll选项，因为违背OC设计初衷。

**Comment by stevezhengshiqi** [comment]
@1457384613gh 
1. occ并非oc官方团队出品，不要以他们的验证器作为基准，也不推荐使用
2. `EnableForAll` 是mod版oc有的特性，如果occ可以切换标准版和mod版，请切换
3. 唯一官方标准版oc config请参考 https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Sample.plist ，其他均为非官方。此仓库每次编辑均通过官方唯一检查器 `ocvalidate` 验证，没有任何错误。
