### ISSUE TITLE
I think trim support patch is also needed for some SATA SSD

### ISSUE THREAD

**Issue by buliaoyin** [daliansky/XiaoMi-Pro#74]
I got an Intel 5400s with M.2 SATA interface, the system report said "TRIM Support: No" by default, so I need to add that patch back, or the SLC cache in this SSD won't be freed after been fully occupied.

It seems MacOS enable trim support default for NVME SSDs, but not the SATA ones. For default NVME SSD such as PM961, it's no harm to add this patch, but for 3party SATA ones, it's needed.

**Comment by stevezhengshiqi** [comment]
@buliaoyin Thank you for advice. I will add back Trim patch. I didn't consider the situation for SATA too much.

**Comment by stevezhengshiqi** [comment]
Added.
