### ISSUE TITLE
HDMI bug sound and screen

### ISSUE THREAD

**Issue by Raphencoder** [daliansky/XiaoMi-Pro#76]
Hi, I have a little bug with HDMI, sometimes when I connect the HDMI, the screen of the Xiaomi turns black and I can't do nothing except reboot. When it's working I have sound issues, the sound doesn't work on the TV...

**Comment by stevezhengshiqi** [comment]
@Raphencoder Hi, according to README, if you have HDMI problem, please reopen the lid. 
For the sound issue, you have to change output source. The method is click the Sound button on the top bar and switch the output source to TV.

**Comment by Raphencoder** [comment]
@stevezhengshiqi, Yes but what do you mean by reopen the lid ? (Sorry for my english..)
Even if I change the output sound in HDMI, the sound does not always work..

**Comment by stevezhengshiqi** [comment]
@Raphencoder Reopen the lid I mean close the lid and then open it.

**Comment by Raphencoder** [comment]
@stevezhengshiqi Ah understand thank you !
