### ISSUE TITLE
ALCPlug Fix kills Mojave

### ISSUE THREAD

**Issue by mj1687** [daliansky/XiaoMi-Pro#79]
I discovered this by myself two days ago.

I did notice this because I was trying to update from HighSierra to Mojave, and after the update MacOS died.

Symptoms:
    Without verbose: Apple Logo, infinite loading
    With verbose: log stops after a while 

Test that I have done: 
       From Mojave to High Sierra -> Died
       Format, Mojave booted, installed clover + alcplugfix -> Died
       Format, Mojave booted, installed clover -> I'm writing from Mojave 

Unfortunately I don't have a log, I know that without a log it's pretty much useless but..I mean just to inform you that In my case this is happened

Mi Notebook pro: i7,8gb,mx150

**Comment by stevezhengshiqi** [comment]
Yes, you are right. If you don’t have trouble shooting file, I can’t hep you. I can make sure ALCPlugFix won’t cause KP if the system is unmodified, both in Mojave and Hogh Sierra.

**Comment by mj1687** [comment]
ok so you are pretty much sure that with the current release this should not happen? I mean i could make a try by downloading the repository now with your latest commits. (On my mi notebook i'm using the latest release)

**Comment by stevezhengshiqi** [comment]
Yes. I am pretty sure clean install + v1.2.8 release work good in 10.13/14.

**Comment by mj1687** [comment]
Ok I'll let u know if mojave dies again, thanks and sorry for the report without a log

**Comment by mj1687** [comment]
actually, i noticed only now that you're providing some bios update instructions in the BIOS folder and i am on a very old build of the bios..could it be te cause of this situation?

**Comment by stevezhengshiqi** [comment]
BIOS should not affect. I have tested on v0301 and v0502 and v0603.

**Comment by mj1687** [comment]
So, I've done lot of things that I don't now which one of them was the right one to get it work but now it works.

- I've updated the bios and the ME firmware
- Updated clover with the latest commits from your repository
- Installed the alc fix but this time by exectuing the install*Chinese things*.command and not the install.command

**Comment by mj1687** [comment]
So I think that you can close this issue, thanks for your work

**Comment by johnnync13** [comment]
@stevezhengshiqi how Can i create script for alc255? jack 3.5 has the same problem on Air
