### ISSUE TITLE
[BUG] Unplugging HDMI turns the screen off.

### ISSUE THREAD

**Issue by kvn1351** [daliansky/XiaoMi-Pro#8]
When I unplug the HDMI cable, the notebook's screen goes dark and never turns back on again.

I guess that the display driver crashes.

OS version: 10.13.3

**Comment by gplast** [comment]
You can enable the laptop screen again by closing the lid while the HDMI is connected and the open the lid again, both screen will be working(in my case thats what i do every time).

**Comment by kvn1351** [comment]
@gplast I'll try that and let you know.

**Comment by daliansky** [comment]
Open `hidpi`, it will automatically correct your monitor's EDID, you can solve the black screen problem, while the external HDMI monitor is working properly
