### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by tcollard** [daliansky/XiaoMi-Pro#82]
Hi, I bought a xiaomi notebook pro a week ago and I tried to install Mojave on it, but I've come across several issues.
When there is the progress bar on Mojave install, near the end, it's rebooting and a message appear to say there where a fatal error. I tried with different version of clover and with older EFI folder from your repository with the same result every time.
So I try to install High Sierra and it ask to plug a mouse, even with different mouses, it's not recognised and I'm stuck to that.

By the way, I did an hackintosh on the same model in June, it was working perfectly, but with the new one it doesn't work and I don't know why. I know that the only difference is the version of the bios, that is the latest version : XMAKB5R0P0603
 
Do you have any idea how to resolve my problem?

Thanks in advance

**Comment by Menchen** [comment]
> @tcollard Hi, maybe you are using a PM981 SSD for recent models, which I wrote in [README.md](https://github.com/daliansky/XiaoMi-Pro/blob/master/README.md). PM981 's serial number starts with `MZVLB` and PM961 starts with `MZVLW`.

My mi pro is coming soon and just want to know what ssd do you recommend to buy in case that mine come with PM981... (ordered about a month ago)

**Comment by tcollard** [comment]
Ah, yes it's that. I gonna try to patch it, or maybe change for PM961.

**Comment by stevezhengshiqi** [comment]
@Menchen For NVME SSD, Samsung 960 EVO or 970 EVO perform good for me. A complete SSD list is at here: https://www.tonymacx86.com/buyersguide/building-a-customac-hackintosh-the-ultimate-buyers-guide/#Solid_State_Drives .
