### ISSUE TITLE
Windows Boot

### ISSUE THREAD

**Issue by paajake** [daliansky/XiaoMi-Pro#84]
I have two ssd one with the hackingtosh and the other with windows, if I try to boot to windows through clover boot menu, I get a blue screen, but when I use F12 and boot from the windows drive directly it works fine, help please... I want to use the Bluetooth

**Comment by Menchen** [comment]
Try linux using mac VM method  first? Sound better than a double boot just for Bluetooth...

**Comment by paajake** [comment]
The VM method worked for the bluetooth, side note, I tried it with virtual box initially and it didn't work, it worked with VmWare Fusion as suggested in the article.

Haven't found a solution to the bluescreen issue though
