### ISSUE TITLE
Another microphone problem

### ISSUE THREAD

**Issue by Drun555** [daliansky/XiaoMi-Pro#85]
So, in 1.2.8 you guys change something in config.plist? My mic doesn't work, and this [thread](https://github.com/stevezhengshiqi/XiaoMi-Pro/issues/13) is useless now (because in .plist layout-id injected by another way, I guess - so tell me if I'm wrong). What I need to do now?

(here's how layout-id injected now, I think)
```
	<key>Devices</key>
	<dict>
		<key>Audio</key>
		<dict>
			<key>Inject</key>
			<string>No</string>
		</dict>
		<key>Properties</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
			<dict>
				<key>layout-id</key>
				<data>YwAAAA==</data>
			</dict>
```

**Comment by stevezhengshiqi** [comment]
@Drun555 Hi, you are using a i5 or i7 device?

**Comment by Drun555** [comment]
I'm using i7-based version. It's something new, right? If you need any additional information - I can provide it.

**Comment by Drun555** [comment]
I'm also tried installation of ALCFix (don't know why), and it's don't work too.

**Comment by stevezhengshiqi** [comment]
@Drun555 i7 should work without patch `config.plist`, just like mine. You can try to replace the CLOVER folder from 1.2.8 release completely(delete and then copy). Then run the `ALCPlugFix` and restart.

**Comment by stevezhengshiqi** [comment]
@Drun555 Don't say that. The instruction is not clear enough.

**Comment by baihulc** [comment]
I'm using i5 mi pro, mic doesn't work properly when i plug in a headphone,  i tried inject lay-out 28&99, it just show build-in and not work well. Any suggestions?

**Comment by stevezhengshiqi** [comment]
@baihulc headphone is another issue. It's off topic and you can open a new one.
