### ISSUE TITLE
Clean ALCPlugFix folder

### ISSUE THREAD

**Issue by orditeck** [daliansky/XiaoMi-Pro#87]
Hi,

I just successfully upgraded from 10.13 to 10.14. At first I had kernel panic when booting into MacOS Install partition but after upgrading my EFI folder to v1.2.8 it worked just fine.

After booting, I noticed that the ALCPlugFix wasn't working anymore. I remembered when first doing it it took me some tries to get it to work.

So I'm opening this issue to suggest to clean this folder a little.

From my experiences, `install.sh` **doesn't work**. Also, it's using relative path so you'd have to `cd` into that directory to make it works. It should be removed.

`install.command` works fine. It's using absolute path by defining `path=${0%/*}`. It also clears the kext caches. `install双击自动安装.command` is the equivalent of `install.command` and could be removed OR renamed to `chinese_install.command` (and then `install.command` would become `english_install.command`).

`uninstall.command` works. `install双击自动卸载ALCPlugFix.command` is the same as `uninstall.command` but with one more output (`Uninstalling the ALCPlugFix daemon is complete!`).

Here's my final files structure suggestions:
```
- fix/
- fix/ALCPlugFix
- fix/good.win.ALCPlugFix.plist
- fix/hda-verb
- english_install.command
- chinese_install.command
- english_uninstall.command
- chinese_uninstall.command
- README.md (so that there are instructions when browsing with github)
```

I can open a PR if you'd like.

**Comment by paajake** [comment]
Did you use the auto update via app store or you reinstalled the hackingtosh with 10.14 from scratch ?

**Comment by orditeck** [comment]
@paajake auto update! Incredibly easy. I was ready for some struggle and got none. 

My laptop is my main working computer so there are lot of stuffs installed. brew, apache, multiple php versions, ruby, python, node w/ n, npm etc etc. Running 2 external monitors (LG 24" UltraWide QHD + LG 29" Ultrawide FHD) with laptop's clamshell closed.

I just had to re-do the ALCPlugFix like I said, and that's it.

**Comment by stevezhengshiqi** [comment]
@orditeck Hi, thank you so much for your suggestion. If you have time, it would be really nice that you can open a PR.  `install.sh` is a legacy item and should be removed. I will add Credit in README.

**Comment by orditeck** [comment]
It's the least I can do! PR #88
