### ISSUE TITLE
驱动里面的 Info.plist 文件换行符是widows格式下的

### ISSUE THREAD

**Issue by yar999** [daliansky/XiaoMi-Pro#9]
CLOVER/kexts/Other目录里面各个驱动里面的 Info.plist 文件换行符是widows格式下的, 需要转成 Unix 格式下的.不然会无法启动黑苹果

![1](https://user-images.githubusercontent.com/7338900/35469677-55b0c194-0375-11e8-8921-215bbf26a6c7.png)
![2](https://user-images.githubusercontent.com/7338900/35469678-55e07f88-0375-11e8-9eb5-51d5e0fcb683.png)

**Comment by daliansky** [comment]
好的，下个更新版本我会重点关注它
