### ISSUE TITLE
Update to Mojave - GeekBench4

### ISSUE THREAD

**Issue by gplast** [daliansky/XiaoMi-Pro#91]
Hello all and thank you again for this great repository and the support that we have from everyone.

I just want to say that i also updated to Mojave from App Store directly using version 1.2.8 without any problem. I have Xiaomi i5/8GB and im using 2 Dell U2417H  screens connected with HDMI and Usb-C Xiaomi original hub with closed lid. I didn't have to run the audio fix, the audio was working without any problem after the update. I had to run kext utility in order to detect the trackpad only.  Everything is smooth and i'm using MacBook 15.2 smbios.

I also like to say that i have triple boot on my Xiaomi, Hackintosh, Linux Mint 18.2 and Windows 10. I run all profiles that you created @stevezhengshiqi and also run GeekBench on Linux and Windows. See the scores bellow:
Hackintosh: Battery: 10842, Balance: 14000, Performance: 14800
Linux: 13800
Windows: 13800

So it seems that the power management on hackintosh are way better that the other two compared to the performance profile that you created. This is just to have a picture how well this hackintosh works :)

Thank you again!!!

**Comment by paajake** [comment]
@gplast  I will need notes on that triple boot please, I can't seem to get even windows and hackingtosh to dual-boot

**Comment by paajake** [comment]
I have Hackingtosh and windows on separate drives, if I try to boot windows through clover I get a blues screen but when I boot windows using F12 it works as mentioned here #84

**Comment by alexmenn** [comment]
I have i7 version and with CPUfriend provided by @daliansky I only get 12k score in geekbench!! Very weird

**Comment by alexmenn** [comment]
It worked downloading again full EFI and replacing it. Thank you :)

**Comment by paajake** [comment]
@mwarf no I haven't found a solution, using the F12 for now

**Comment by stevezhengshiqi** [comment]
@paajake @mwarf I see a workaround at https://github.com/daliansky/XiaoMi-Pro/issues/93. You guys can try the `AptioMemoryFix.efi.zip` provided. Hope to hear great news.

**Comment by stevezhengshiqi** [comment]
@mwarf Rename and replace.

**Comment by mwarf** [comment]
@stevezhengshiqi thank you, this fixed the problem, tested through multiple reboots in both Windows 10 Pro x64 and Mojave 10.14 - Very nice!@paajake

**Comment by paajake** [comment]
works well for me too. Thanks!
