### ISSUE TITLE
Hidpi only support 1344 x 756

### ISSUE THREAD

**Issue by baihulc** [daliansky/XiaoMi-Pro#94]
Hi, bro. thks for ur work on hidpi, but it seems only work well when i choose 1344 x 756 in my mi pro. On that solution it looks weird. 1600x900 may better, but it can't fill the screen.  can u fix it? plzzz

**Comment by baihulc** [comment]
@paajake OK, I will try it. glitches on boot may acceptable. Is there still a small-screen problem on wake-up? that's annoy one only fix by reboot.

**Comment by paajake** [comment]
@baihulc it's not just the small screen or glitches on boot, the screen actually flickers too which is very annoying, so you'll definitely require a reboot, fortunately its a fast machine so doesn't take long to reboot

**Comment by stevezhengshiqi** [comment]
@baihulc Hi, I wrote in README and in the script that people should select 1344 resolution. Other resolution higher than 1344x756 is not supported.
