### ISSUE TITLE
Will the instructions here work for a first generation XiaoMi Air? 

### ISSUE THREAD

**Issue by hyperparsa** [daliansky/XiaoMi-Pro#98]
The CPU is a 6th gen i7-6500u. Graphics is 940mx. I'm not familiar with the rest of the hardware but should be similar to the Pro.

**Comment by stevezhengshiqi** [comment]
@hyperparsa Hi, I am sorry to say that to a large extent the instructions here don’t fit with Air. Additionally, you have a 6th generation CPU, maybe a skylake, which has different power management and SMBus from Kabulake.

**Comment by hyperparsa** [comment]
@stevezhengshiqi Ah, okay. Thanks!

**Comment by Vichearith** [comment]
Hello!
And on this model which is a 7th generation CPU, does it work? Xiaomi Air 12.5 Pouces Intel Core m3 i5 CPU
https://s.click.aliexpress.com/e/bVwQssfP

**Comment by stevezhengshiqi** [comment]
@Vichearith You have to test it on your own since I don't have the device you mentioned above.

**Comment by influenist** [comment]
Please see the following builds for air:
12.5 6y30 - https://github.com/johnnync13/EFI-Xiaomi-Notebook-air-12-5
12.5 7y30 - https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS
13.3 Gen1 - https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen
13.3 2018 - https://github.com/johnnync13/Xiaomi-Mi-Air
 
I have my hands on the 12.5 - i5 Processor with 8GB as well. Seen I will add this build soon to my Github.

**Comment by johnnync13** [comment]
Yes, of course @influentist

**Comment by stevezhengshiqi** [comment]
Sure. Thank you all @influenist @johnnync13  for the great work! I will add it after some updates.

**Comment by influenist** [comment]
Update the README: 
https://raw.githubusercontent.com/influenist/Mi-NB-Gaming-Laptop-MacOS/master/README.md
